import type { LegalContentBundle } from "./legalContent.types";

export const legalContentEs: LegalContentBundle = {
  releaseDate: "13 de abril de 2026",
  documents: {
    terms: {
      eyebrow: "Términos del Servicio",
      title: "Términos del Servicio de KŌMA Studio",
      summary:
        "Reglas que rigen el acceso a KŌMA Studio, las integraciones opcionales, las áreas comunitarias y el uso de las funciones de escritorio y conectadas a la web.",
      highlights: [
        "KŌMA Studio combina una aplicación de escritorio con autenticación web, actualizaciones, soporte y servicios remotos opcionales.",
        "Sigues siendo responsable de los derechos, permisos y la legalidad de los archivos, prompts, enlaces y materiales que envíes o publiques.",
        "Las funciones, integraciones y controles de seguridad pueden cambiar cuando cambien las leyes, los proveedores o los requisitos de prevención del abuso.",
      ],
      sections: [
        { title: "1. Alcance del servicio", paragraphs: ["KŌMA Studio ofrece herramientas de limpieza, redraw, OCR, traducción, rotulación, automatización de flujo, publicación asistida y otras funciones de productividad para scanlation. Parte de las funciones se ejecutan íntegramente en el dispositivo; otras dependen de infraestructura remota para cuenta, soporte, actualizaciones, servicios gestionados o integraciones activadas por el usuario.", "El servicio puede evolucionar con el tiempo. Podemos añadir, modificar, sustituir o retirar funciones, proveedores, catálogos de modelos, requisitos de seguridad o reglas de compatibilidad cuando sea necesario para la operación del producto, el cumplimiento legal o la integridad de la infraestructura."] },
        { title: "2. Cuenta, elegibilidad y seguridad", paragraphs: ["Debes proporcionar datos de registro exactos, mantener tus credenciales en secreto y usar el servicio solo si puedes celebrar un acuerdo vinculante conforme a la ley aplicable. El servicio no está destinado a menores de la edad mínima exigida por la ley aplicable para usar servicios en línea sin autorización parental o del tutor.", "Podemos exigir verificación de correo electrónico, validación de dispositivo de confianza, flujo de travel token, CAPTCHA, límites de tasa, actualización obligatoria de la app, revisión de sesión, restricciones temporales y otros controles razonables para proteger cuentas, integraciones y la plataforma."], bullets: ["Eres responsable de la actividad realizada en tu cuenta, salvo que la ley disponga lo contrario.", "Está prohibido compartir credenciales, superar restricciones técnicas o usar el servicio para automatizar fraude o abuso.", "Podemos suspender o terminar el acceso cuando detectemos riesgo de seguridad, conducta ilícita o incumplimiento grave de estos documentos."] },
        { title: "3. Contenido del usuario, derechos y uso aceptable", paragraphs: ["La titularidad de tu contenido sigue siendo tuya. Sin embargo, concedes a KŌMA Studio los derechos limitados necesarios para alojar, transmitir, almacenar en caché, transformar, mostrar o procesar ese contenido exclusivamente para ejecutar las funciones solicitadas, mantener la seguridad y prestar soporte.", "Declaras que dispones de los derechos, licencias, autorizaciones y bases legales necesarias para enviar, procesar, publicar o compartir cualquier imagen, texto, prompt, log, adjunto o enlace utilizado en el servicio. KŌMA Studio no te concede derechos sobre obras de terceros ni valida tu cadena de titularidad."], bullets: ["No uses el servicio para vulnerar derechos de autor, marcas, privacidad, confidencialidad, derechos de la personalidad o seguridad de la plataforma.", "No envíes malware, phishing, material ilícito, reclutamiento engañoso ni contenido comunitario abusivo.", "Podemos eliminar, ocultar, bloquear o reportar contenido que genere riesgo jurídico, de seguridad, reputacional u operacional."] },
        { title: "4. Servicios de terceros e integraciones", paragraphs: ["Funciones como Blogger, Imgur, Discord webhook, proveedores de IA con clave propia y otros conectores solo funcionan cuando los activas deliberadamente. Al iniciar estos flujos, KŌMA Studio puede enviar el contenido seleccionado, credenciales, metadatos e instrucciones de ejecución necesarias para completar la acción solicitada.", "Los servicios de terceros operan bajo sus propios términos, avisos de privacidad, reglas de conservación, límites y compromisos de disponibilidad. No somos responsables de indisponibilidad, cambios de política, bloqueos de cuenta, tratamiento de datos o perjuicios causados por proveedores que elegiste conectar o por credenciales configuradas por ti."] },
        { title: "5. Disponibilidad, responsabilidad y actualizaciones", paragraphs: ["El servicio se presta sobre una base de disponibilidad y actualización continua. En la máxima medida permitida por la ley, KŌMA Studio no responde por daños indirectos, pérdida de beneficios, retrasos editoriales, fallos de publicación externa, indisponibilidad de proveedores o perjuicios causados por un uso ilícito o no autorizado del servicio por el usuario.", "Nada de estos términos excluye derechos irrenunciables del consumidor o de privacidad. Podemos actualizar estos términos y los avisos relacionados cuando cambien el producto, la ley, los proveedores o el perfil de riesgo. La versión vigente se publica en el Centro Legal y puede requerirse una nueva aceptación para continuar usando el servicio."] },
      ],
    },
    privacy: {
      eyebrow: "Política de Privacidad",
      title: "Política de Privacidad de KŌMA Studio",
      summary:
        "Cómo KŌMA Studio recopila, utiliza, comparte, conserva y protege datos personales relacionados con cuentas, soporte, seguridad, integraciones y funciones comunitarias.",
      highlights: [
        "KŌMA Studio actúa como responsable del tratamiento en las operaciones descritas aquí, salvo cuando un tercero actúa por cuenta propia como responsable independiente.",
        "Tratamos datos de cuenta, dispositivo, soporte, moderación e integraciones para operar el servicio, proteger a los usuarios y cumplir obligaciones legales.",
        "No usamos cookies publicitarias en el producto actual y no vendemos datos personales.",
      ],
      sections: [
        { title: "1. Alcance y papel como responsable", paragraphs: ["Esta política se aplica a la aplicación de escritorio de KŌMA Studio, a los flujos web de autenticación, a las operaciones de soporte, a los flujos de bug report, a las áreas comunitarias y a los servicios conectados. Para los tratamientos descritos aquí, KŌMA Studio actúa como responsable del tratamiento, salvo cuando otro proveedor define de forma autónoma los fines y medios del tratamiento.", "Los proveedores de correo electrónico, IA conectada por ti, plataformas externas de publicación y socios de infraestructura pueden actuar como encargados o responsables independientes según la actividad. Sus propios documentos legales también se aplican a los datos que tratan por cuenta propia."] },
        { title: "2. Categorías de datos personales", paragraphs: ["Podemos recopilar datos de registro y cuenta, como nombre para mostrar, correo electrónico, estado de verificación, identificadores de cuenta, registros de sesión, intentos de acceso, identificadores de dispositivo de confianza, señales de IP vinculadas a seguridad y diagnósticos de la máquina o de la app necesarios para proteger el acceso y operar el servicio.", "También podemos tratar envíos de soporte y bug report, publicaciones comunitarias e historial de moderación, configuraciones de integración, destinos de webhook, identificadores de proveedores y los archivos, capturas, prompts, logs, adjuntos o metadatos que decidas enviar mediante el producto."] },
        { title: "3. Finalidades y bases legales", paragraphs: ["Tratamos datos personales para crear y administrar cuentas, autenticar sesiones, entregar actualizaciones, responder soporte, investigar fallos, operar áreas comunitarias, prevenir abuso, proteger la infraestructura, cumplir obligaciones legales, hacer valer nuestros términos y resolver incidentes de seguridad.", "Según el contexto, las principales bases legales son la ejecución del contrato, el interés legítimo en la seguridad y la fiabilidad del servicio, el cumplimiento de obligaciones legales y el consentimiento o la acción afirmativa del usuario para funciones opcionales, como bug reports, integraciones voluntarias, conexiones BYOK o comunicaciones opcionales. Si estás en el Espacio Económico Europeo, Reino Unido, Brasil o jurisdicción similar, puedes tener derechos legales adicionales descritos más abajo."] },
        { title: "4. Compartición, transferencias internacionales y terceros", paragraphs: ["Compartimos datos personales solo cuando es necesario para operar el servicio, cumplir tu instrucción, atender una obligación legal, prevenir fraude o defender derechos. Los destinatarios habituales pueden incluir proveedores de alojamiento y base de datos, proveedores de correo transaccional, herramientas de soporte, integraciones opcionales como Blogger, Imgur, Discord webhook y servicios de IA que conectes.", "Como estos proveedores pueden operar en distintos países, los datos personales pueden transferirse internacionalmente. Cuando procede, adoptamos salvaguardias contractuales, organizativas y técnicas adecuadas a la transferencia y al riesgo, reconociendo que determinados proveedores tratarán datos bajo sus propios marcos legales y políticas."] },
        { title: "5. Conservación, seguridad y menores", paragraphs: ["Conservamos datos personales solo durante el tiempo necesario para las finalidades descritas en esta política, incluida la prestación del servicio, prevención del fraude, supervisión de seguridad, análisis de incidentes, defensa jurídica y cumplimiento normativo. Distintas categorías pueden tener plazos distintos, y algunos registros no pueden eliminarse de inmediato cuando la ley exige conservación.", "Usamos medidas como hash de contraseña, controles de sesión, tokens de corta duración, validación de webhooks, logs de auditoría, límites de tasa, controles de acceso y revisiones de seguridad para reducir acceso no autorizado o abuso. Ningún sistema es absolutamente seguro, por lo que debes evitar enviar datos sensibles innecesarios. El servicio no está dirigido a menores de la edad digital mínima aplicable."] },
        { title: "6. Tus derechos y contacto", paragraphs: ["Sujeto a la ley aplicable, puedes solicitar acceso, confirmación de tratamiento, rectificación, portabilidad cuando proceda, supresión, anonimización, oposición, limitación, retirada del consentimiento cuando ese sea el fundamento e información sobre destinatarios, conservación, salvaguardias y decisiones automatizadas. Podemos solicitar verificación razonable de identidad antes de atender una solicitud y conservar un registro mínimo de la solicitud y de nuestra respuesta con fines de responsabilidad proactiva.", "Las solicitudes sobre privacidad, datos personales, cookies o avisos legales deben enviarse al canal oficial de soporte en {supportUrl}. Intentamos responder dentro de los plazos exigidos por la legislación aplicable, incluido el plazo de un mes del GDPR cuando corresponda."] },
      ],
    },
    cookies: {
      eyebrow: "Política de Cookies",
      title: "Política de Cookies de KŌMA Studio",
      summary: "Cómo KŌMA Studio utiliza cookies, almacenamiento local y tecnologías relacionadas para autenticación, seguridad y funcionamiento del producto.",
      highlights: [
        "El producto actual depende principalmente de cookies estrictamente necesarias y almacenamiento local indispensables para autenticar usuarios y mantener la seguridad.",
        "La aplicación de escritorio también conserva parte de los datos localmente mediante Electron y almacenamiento de la app, no solo mediante cookies del navegador.",
        "Si KŌMA Studio introduce analytics, publicidad o personalización basada en cookies no estrictamente necesarias, esta política y los controles relacionados se actualizarán antes de que ese uso se convierta en estándar.",
      ],
      sections: [
        { title: "1. Tecnologías utilizadas", paragraphs: ["KŌMA Studio puede utilizar cookies HttpOnly, cookies de sesión, almacenamiento del navegador, almacenamiento de la app de escritorio, preferencias de correo recordado, identificadores de dispositivo y tecnologías equivalentes para mantener el inicio de sesión, proteger sesiones, recordar el estado del producto y dar soporte a flujos de autenticación, recuperación y actualización."] },
        { title: "2. Cookies estrictamente necesarias", paragraphs: ["Las cookies estrictamente necesarias se utilizan para autenticación, continuidad de sesión, prevención del fraude, detección de abuso, recuperación de cuenta, verificaciones de seguridad y acceso a áreas protegidas. Estas tecnologías son necesarias para prestar el servicio solicitado por el usuario y no se utilizan con fines publicitarios en el producto actual."], bullets: ["Establecimiento de sesión y expiración controlada.", "Verificaciones de seguridad y antiabuso durante el inicio de sesión y la recuperación de cuenta.", "Continuidad de acceso cuando debe mantenerse un estado protegido de la cuenta."] },
        { title: "3. Almacenamiento local y persistencia en escritorio", paragraphs: ["KŌMA Studio puede guardar preferencias no sensibles localmente, como estado de la interfaz, idioma seleccionado, correo recordado, presets, elección del canal de actualización o ajustes de conveniencia del flujo de trabajo. Configuraciones de integración o tokens también pueden almacenarse localmente cuando la función lo requiera y el producto esté diseñado para mantener esa información en el dispositivo cuando sea posible."] },
        { title: "4. Cómo gestionar estas tecnologías", paragraphs: ["Puedes borrar cookies y almacenamiento local desde tu navegador o cerrar sesión y restablecer el estado local desde la app cuando esa opción esté disponible. Bloquear o eliminar tecnologías estrictamente necesarias puede impedir el inicio de sesión, la recuperación de cuenta, el acceso a la facturación o el funcionamiento normal de las áreas protegidas del producto."] },
      ],
    },
    content: {
      eyebrow: "Política de Uso y Contenido",
      title: "Política de Uso y Contenido de KŌMA Studio",
      summary: "Normas para archivos enviados, contenido comunitario, bug reports, publicación externa, moderación y uso lícito de las funciones de KŌMA Studio.",
      highlights: [
        "Solo puedes procesar o publicar contenido cuando tengas derechos o autorización legal para hacerlo.",
        "Las funciones comunitarias y de publicación pueden moderarse, restringirse o retirarse cuando generen riesgo jurídico, abuso o riesgo de seguridad.",
        "Los bug reports y las integraciones opcionales pueden enviar capturas, logs, adjuntos o archivos seleccionados a servicios de terceros cuando activas esos flujos.",
      ],
      sections: [
        { title: "1. Derechos y permisos sobre el contenido", paragraphs: ["Las herramientas de edición, OCR, traducción, redraw, rotulación y publicación no te conceden derechos sobre obras de terceros. Eres la única persona responsable de comprobar si el uso del contenido es lícito en tu jurisdicción y de contar con las licencias, permisos, consentimientos u otra base legal necesaria para ese uso."] },
        { title: "2. Áreas comunitarias y moderación", paragraphs: ["Las publicaciones, perfiles, adjuntos, candidaturas y reportes enviados a espacios comunitarios como Scanlation Feed pueden ser revisados por sistemas automatizados y moderadores humanos. Podemos ocultar, etiquetar, eliminar, restringir o escalar contenido que parezca engañoso, abusivo, ilícito, infractor, inseguro o incompatible con la integridad de la plataforma."], bullets: ["No publiques phishing, malware, spam, suplantación ni ofertas de reclutamiento fraudulentas.", "No expongas datos personales de terceros sin base legal.", "No utilices áreas comunitarias para coordinar abuso, acoso o infracción."] },
        { title: "3. Publicación externa, proveedores de IA e integraciones", paragraphs: ["Al usar Blogger, Imgur, Discord webhook, proveedores de IA, subidas u otros conectores externos, instruyes a KŌMA Studio para transmitir los archivos, prompts, resultados, metadatos e instrucciones técnicas necesarios para completar la acción. Es tu responsabilidad verificar que el destino, la audiencia y los permisos sean adecuados antes de iniciar la transferencia."] },
        { title: "4. Bug reports y diagnósticos", paragraphs: ["Los flujos de bug report pueden incluir la captura actual, adjuntos, logs seleccionados, diagnósticos del entorno, contexto de la cuenta y detalles técnicos que nos ayuden a investigar el problema. Revisa todo el material antes de enviarlo. Cuando el flujo use servicios como Discord webhook o Imgur, el material seleccionado se enviará a esos servicios para procesar el reporte."] },
        { title: "5. Medidas de aplicación", paragraphs: ["Podemos limitar, suspender, eliminar o terminar el acceso a cualquier función, archivo, integración o cuenta cuando creamos razonablemente que ello es necesario para evitar daños, cumplir la ley, investigar abusos, responder a una denuncia válida, proteger a usuarios o preservar la integridad del servicio. Las infracciones repetidas o graves pueden dar lugar a restricciones permanentes."] },
      ],
    },
  },
};
