import type { LegalContentBundle } from "./legalContent.types";

export const legalContentDe: LegalContentBundle = {
  releaseDate: "13. April 2026",
  documents: {
    terms: {
      eyebrow: "Nutzungsbedingungen",
      title: "Nutzungsbedingungen von KŌMA Studio",
      summary: "Regeln für den Zugang zu KŌMA Studio, optionale Integrationen, Community-Bereiche und die Nutzung von Desktop- und webbasierten Funktionen.",
      highlights: ["KŌMA Studio verbindet eine Desktop-Anwendung mit Web-Authentifizierung, Updates, Support und optionalen Remote-Diensten.", "Sie bleiben für Rechte, Berechtigungen und die Rechtmäßigkeit der Dateien, Prompts, Links und Inhalte verantwortlich, die Sie übermitteln oder veröffentlichen.", "Funktionen, Integrationen und Sicherheitskontrollen können sich ändern, wenn sich Gesetze, Anbieter oder Anforderungen zur Missbrauchsprävention ändern."],
      sections: [
        { title: "1. Leistungsumfang", paragraphs: ["KŌMA Studio bietet Werkzeuge für Cleaning, Redraw, OCR, Übersetzung, Typesetting, Workflow-Automatisierung, unterstützte Veröffentlichung und weitere Produktivitätsfunktionen für Scanlation. Ein Teil der Funktionen läuft vollständig auf dem Gerät; andere hängen von Remote-Infrastruktur für Konto, Support, Updates, verwaltete Dienste oder vom Nutzer aktivierte Integrationen ab.", "Der Dienst kann sich im Laufe der Zeit weiterentwickeln. Wir können Funktionen, Anbieter, Modellkataloge, Sicherheitsanforderungen oder Kompatibilitätsregeln hinzufügen, ändern, ersetzen oder einstellen, wenn dies für den Produktbetrieb, die rechtliche Compliance oder die Integrität der Infrastruktur erforderlich ist."] },
        { title: "2. Konto, Berechtigung und Sicherheit", paragraphs: ["Sie müssen korrekte Registrierungsdaten angeben, Ihre Zugangsdaten vertraulich behandeln und den Dienst nur nutzen, wenn Sie nach dem für Sie geltenden Recht einen verbindlichen Vertrag schließen können. Der Dienst richtet sich nicht an Kinder unter dem nach anwendbarem Recht erforderlichen Mindestalter für die Nutzung von Online-Diensten ohne Zustimmung von Eltern oder Erziehungsberechtigten.", "Wir können E-Mail-Verifizierung, die Validierung vertrauenswürdiger Geräte, Travel-Token-Flows, CAPTCHA, Rate Limits, verpflichtende App-Updates, Sitzungsprüfungen, vorübergehende Einschränkungen und andere angemessene Kontrollen verlangen, um Konten, Integrationen und die Plattform zu schützen."], bullets: ["Sie sind für die Aktivitäten auf Ihrem Konto verantwortlich, soweit das Gesetz nichts anderes bestimmt.", "Es ist untersagt, Zugangsdaten zu teilen, technische Beschränkungen zu umgehen oder den Dienst zur Automatisierung von Betrug oder Missbrauch zu verwenden.", "Wir können den Zugang aussetzen oder beenden, wenn wir ein Sicherheitsrisiko, rechtswidriges Verhalten oder einen schwerwiegenden Verstoß gegen diese Dokumente feststellen."] },
        { title: "3. Nutzerinhalte, Rechte und zulässige Nutzung", paragraphs: ["Das Eigentum an Ihren Inhalten verbleibt bei Ihnen. Sie gewähren KŌMA Studio jedoch die begrenzten Rechte, die erforderlich sind, um diese Inhalte ausschließlich zur Ausführung der angeforderten Funktionen, zur Aufrechterhaltung der Sicherheit und zur Erbringung von Support zu hosten, zu übertragen, zwischenzuspeichern, zu transformieren, anzuzeigen oder zu verarbeiten.", "Sie versichern, dass Sie über die erforderlichen Rechte, Lizenzen, Genehmigungen und Rechtsgrundlagen verfügen, um Bilder, Texte, Prompts, Logs, Anhänge oder Links, die im Dienst verwendet werden, einzusenden, zu verarbeiten, zu veröffentlichen oder zu teilen. KŌMA Studio gewährt Ihnen keine Rechte an Werken Dritter und prüft Ihre Rechtekette nicht."], bullets: ["Nutzen Sie den Dienst nicht, um Urheberrechte, Markenrechte, Datenschutz, Vertraulichkeit, Persönlichkeitsrechte oder die Sicherheit der Plattform zu verletzen.", "Senden Sie keine Malware, Phishing-Inhalte, rechtswidrige Materialien, irreführende Rekrutierung oder missbräuchliche Community-Inhalte.", "Wir können Inhalte entfernen, verbergen, blockieren oder melden, wenn sie rechtliche, sicherheitsbezogene, reputationsbezogene oder operative Risiken schaffen."] },
        { title: "4. Dienste Dritter und Integrationen", paragraphs: ["Funktionen wie Blogger, Imgur, Discord Webhook, BYOK-KI-Anbieter und andere Konnektoren funktionieren nur, wenn Sie diese bewusst aktivieren. Wenn Sie diese Flows auslösen, kann KŌMA Studio den ausgewählten Inhalt, Zugangsdaten, Metadaten und Ausführungsanweisungen übertragen, die für die angeforderte Aktion notwendig sind.", "Dienste Dritter unterliegen ihren eigenen Bedingungen, Datenschutzhinweisen, Aufbewahrungsregeln, Limits und Verfügbarkeitszusagen. Wir sind nicht verantwortlich für Ausfälle, Richtlinienänderungen, Kontosperren, Datenverarbeitung oder Schäden, die durch Anbieter entstehen, die Sie verbinden, oder durch Zugangsdaten, die Sie konfigurieren." ] },
        { title: "5. Verfügbarkeit, Haftung und Aktualisierungen", paragraphs: ["Der Dienst wird auf Basis von Verfügbarkeit und laufenden Aktualisierungen bereitgestellt. Soweit gesetzlich zulässig, haftet KŌMA Studio nicht für mittelbare Schäden, entgangenen Gewinn, redaktionelle Verzögerungen, fehlgeschlagene externe Veröffentlichung, Ausfälle von Anbietern oder Schäden, die durch rechtswidrige oder unbefugte Nutzung des Dienstes durch den Nutzer entstehen.", "Nichts in diesen Bedingungen schließt zwingende Verbraucher- oder Datenschutzrechte aus. Wir können diese Bedingungen und die zugehörigen Hinweise aktualisieren, wenn sich Produkt, Gesetzeslage, Anbieter oder Risikoprofil ändern. Die jeweils aktuelle Version wird im Rechtszentrum veröffentlicht; für die weitere Nutzung kann eine erneute Zustimmung erforderlich sein."] },
      ],
    },
    privacy: {
      eyebrow: "Datenschutzerklärung",
      title: "Datenschutzerklärung von KŌMA Studio",
      summary: "Wie KŌMA Studio personenbezogene Daten im Zusammenhang mit Konten, Support, Sicherheit, Integrationen und Community-Funktionen erhebt, nutzt, teilt, speichert und schützt.",
      highlights: ["KŌMA Studio handelt bei den hier beschriebenen Vorgängen als Verantwortlicher, außer wenn ein Dritter eigenständig als unabhängiger Verantwortlicher auftritt.", "Wir verarbeiten Konto-, Geräte-, Support-, Moderations- und Integrationsdaten, um den Dienst zu betreiben, Nutzer zu schützen und gesetzliche Pflichten zu erfüllen.", "Wir verwenden im aktuellen Produkt keine Werbe-Cookies und verkaufen keine personenbezogenen Daten."],
      sections: [
        { title: "1. Geltungsbereich und Rolle als Verantwortlicher", paragraphs: ["Diese Erklärung gilt für die Desktop-Anwendung von KŌMA Studio, die webbasierten Authentifizierungsflüsse, Support-Vorgänge, Bug-Report-Flows, Community-Bereiche und verbundene Dienste. Für die hier beschriebenen Verarbeitungsvorgänge handelt KŌMA Studio als Verantwortlicher, außer wenn ein anderer Anbieter Zwecke und Mittel der Verarbeitung eigenständig festlegt.", "E-Mail-Anbieter, von Ihnen verbundene KI-Dienste, externe Veröffentlichungsplattformen und Infrastrukturpartner können je nach Tätigkeit als Auftragsverarbeiter oder unabhängige Verantwortliche handeln. Deren eigene Rechtsdokumente gelten ebenfalls für die Daten, die sie für eigene Zwecke verarbeiten."] },
        { title: "2. Kategorien personenbezogener Daten", paragraphs: ["Wir können Registrierungs- und Kontodaten erheben, etwa Anzeigename, E-Mail-Adresse, Verifizierungsstatus, Konto-IDs, Sitzungsprotokolle, Login-Versuche, IDs vertrauenswürdiger Geräte, sicherheitsbezogene IP-Signale und Diagnosedaten von Gerät oder App, die zur Absicherung des Zugangs und zum Betrieb des Dienstes erforderlich sind.", "Darüber hinaus können wir Support- und Bug-Report-Einreichungen, Community-Beiträge und Moderationshistorie, Integrationskonfigurationen, Webhook-Ziele, Anbieterkennungen sowie Dateien, Screenshots, Prompts, Logs, Anhänge oder Metadaten verarbeiten, die Sie über das Produkt übermitteln."] },
        { title: "3. Zwecke und Rechtsgrundlagen", paragraphs: ["Wir verarbeiten personenbezogene Daten, um Konten anzulegen und zu verwalten, Sitzungen zu authentifizieren, Updates auszuliefern, Support zu leisten, Fehler zu untersuchen, Community-Bereiche zu betreiben, Missbrauch zu verhindern, die Infrastruktur zu schützen, gesetzliche Pflichten zu erfüllen, unsere Bedingungen durchzusetzen und Sicherheitsvorfälle zu bearbeiten.", "Je nach Kontext sind die wichtigsten Rechtsgrundlagen Vertragserfüllung, berechtigte Interessen an Sicherheit und Zuverlässigkeit des Dienstes, die Erfüllung gesetzlicher Pflichten sowie Einwilligung oder bestätigende Nutzerhandlung für optionale Funktionen wie Bug Reports, freiwillige Integrationen, BYOK-Verbindungen oder optionale Kommunikation. Wenn Sie sich im Europäischen Wirtschaftsraum, im Vereinigten Königreich, in Brasilien oder einer ähnlichen Rechtsordnung befinden, können zusätzliche gesetzliche Rechte gelten." ] },
        { title: "4. Weitergabe, internationale Übermittlungen und Dritte", paragraphs: ["Wir geben personenbezogene Daten nur weiter, wenn dies für den Betrieb des Dienstes, die Ausführung Ihrer Anweisung, die Erfüllung gesetzlicher Pflichten, Betrugsprävention oder die Verteidigung von Rechten erforderlich ist. Empfänger können insbesondere Hosting- und Datenbankanbieter, Anbieter transaktionaler E-Mail, Support-Tools, optionale Integrationen wie Blogger, Imgur, Discord Webhook und von Ihnen verbundene KI-Dienste sein.", "Da diese Anbieter in verschiedenen Ländern tätig sein können, können personenbezogene Daten international übertragen werden. Soweit erforderlich, setzen wir vertragliche, organisatorische und technische Schutzmaßnahmen ein, die zur Übermittlung und zum Risiko passen, wobei bestimmte Anbieter Daten nach ihren eigenen Rechtsrahmen und Richtlinien verarbeiten." ] },
        { title: "5. Speicherdauer, Sicherheit und Minderjährige", paragraphs: ["Wir speichern personenbezogene Daten nur so lange, wie es für die in dieser Erklärung beschriebenen Zwecke erforderlich ist, insbesondere für die Leistungserbringung, Betrugsprävention, Sicherheitsüberwachung, Vorfallanalyse, Rechtsverteidigung und regulatorische Compliance. Verschiedene Kategorien können unterschiedliche Fristen haben, und manche Aufzeichnungen dürfen nicht sofort gelöscht werden, wenn das Gesetz eine Aufbewahrung verlangt.", "Wir setzen Maßnahmen wie Passwort-Hashing, Sitzungssteuerung, kurzlebige Tokens, Webhook-Validierung, Audit-Logs, Rate Limits, Zugriffskontrollen und Sicherheitsprüfungen ein, um unbefugten Zugriff oder Missbrauch zu reduzieren. Kein System ist vollständig sicher; vermeiden Sie daher die Übermittlung unnötiger sensibler Daten. Der Dienst richtet sich nicht an Kinder unterhalb des anwendbaren digitalen Mindestalters." ] },
        { title: "6. Ihre Rechte und Kontakt", paragraphs: ["Vorbehaltlich des anwendbaren Rechts können Sie Auskunft, Bestätigung der Verarbeitung, Berichtigung, Portabilität soweit verfügbar, Löschung, Anonymisierung, Widerspruch, Einschränkung, Widerruf einer Einwilligung sowie Informationen über Empfänger, Speicherdauer, Schutzmaßnahmen und automatisierte Entscheidungen verlangen. Wir können vor der Bearbeitung einer Anfrage eine angemessene Identitätsprüfung verlangen und eine minimale Dokumentation der Anfrage und unserer Antwort zu Rechenschaftszwecken aufbewahren.", "Anfragen zu Datenschutz, personenbezogenen Daten, Cookies oder rechtlichen Hinweisen müssen über den offiziellen Support-Kanal unter {supportUrl} eingereicht werden. Wir bemühen uns, innerhalb der nach anwendbarem Recht geltenden Fristen zu antworten, einschließlich der DSGVO-Referenzfrist von einem Monat, sofern sie anwendbar ist." ] },
      ],
    },
    cookies: {
      eyebrow: "Cookie-Richtlinie",
      title: "Cookie-Richtlinie von KŌMA Studio",
      summary: "Wie KŌMA Studio Cookies, lokalen Speicher und verwandte Technologien für Authentifizierung, Sicherheit und den Betrieb des Produkts nutzt.",
      highlights: ["Das aktuelle Produkt stützt sich hauptsächlich auf unbedingt erforderliche Cookies und lokalen Speicher, die zur Authentifizierung von Nutzern und zur Aufrechterhaltung der Sicherheit notwendig sind.", "Die Desktop-Anwendung speichert außerdem einen Teil der Daten lokal über Electron und App-Speicher und nicht ausschließlich über Browser-Cookies.", "Wenn KŌMA Studio Analytics, Werbung oder Personalisierung auf Basis nicht unbedingt erforderlicher Cookies einführt, werden diese Richtlinie und die zugehörigen Kontrollen vor diesem Einsatz aktualisiert."],
      sections: [
        { title: "1. Verwendete Technologien", paragraphs: ["KŌMA Studio kann HttpOnly-Cookies, Sitzungs-Cookies, Browser-Speicher, Desktop-App-Speicher, gespeicherte E-Mail-Präferenzen, Gerätekennungen und vergleichbare Technologien einsetzen, um angemeldet zu bleiben, Sitzungen zu sichern, den Produktzustand zu speichern und Authentifizierungs-, Wiederherstellungs- und Update-Flows zu unterstützen."] },
        { title: "2. Unbedingt erforderliche Cookies", paragraphs: ["Unbedingt erforderliche Cookies werden für Authentifizierung, Sitzungsfortführung, Betrugsprävention, Missbrauchserkennung, Kontowiederherstellung, Sicherheitsprüfungen und den Zugang zu geschützten Bereichen eingesetzt. Diese Technologien sind notwendig, um den vom Nutzer angeforderten Dienst bereitzustellen, und werden im aktuellen Produkt nicht für Werbung verwendet."], bullets: ["Aufbau der Sitzung und kontrollierter Ablauf.", "Sicherheits- und Anti-Missbrauchsprüfungen bei Anmeldung und Kontowiederherstellung.", "Zugangskontinuität, wenn ein geschützter Kontostatus aufrechterhalten werden muss."] },
        { title: "3. Lokaler Speicher und Desktop-Persistenz", paragraphs: ["KŌMA Studio kann nicht sensible Präferenzen lokal speichern, etwa den Zustand der Oberfläche, die gewählte Sprache, gemerkte E-Mail-Adressen, Presets, die Wahl des Update-Kanals oder Komforteinstellungen im Workflow. Integrationskonfigurationen oder Tokens können ebenfalls lokal gespeichert werden, wenn die Funktion dies erfordert und das Produkt so gestaltet ist, diese Informationen soweit möglich auf dem Gerät zu halten."] },
        { title: "4. Verwaltung dieser Technologien", paragraphs: ["Sie können Cookies und lokalen Speicher über Ihren Browser löschen oder sich abmelden und den lokalen Zustand in der App zurücksetzen, sofern diese Option verfügbar ist. Das Blockieren oder Löschen unbedingt erforderlicher Technologien kann die Anmeldung, Kontowiederherstellung oder den normalen Betrieb geschützter Produktbereiche verhindern."] },
      ],
    },
    content: {
      eyebrow: "Nutzungs- und Inhaltsrichtlinie",
      title: "Nutzungs- und Inhaltsrichtlinie von KŌMA Studio",
      summary: "Regeln für hochgeladene Dateien, Community-Inhalte, Bug Reports, externe Veröffentlichung, Moderation und die rechtmäßige Nutzung der Funktionen von KŌMA Studio.",
      highlights: ["Sie dürfen Inhalte nur verarbeiten oder veröffentlichen, wenn Sie die Rechte oder eine rechtliche Erlaubnis dafür haben.", "Community- und Veröffentlichungsfunktionen können moderiert, eingeschränkt oder entfernt werden, wenn sie rechtliche Risiken, Missbrauch oder Sicherheitsrisiken verursachen.", "Bug Reports und optionale Integrationen können Screenshots, Logs, Anhänge oder ausgewählte Dateien an Drittanbieter senden, wenn Sie diese Flows auslösen."],
      sections: [
        { title: "1. Rechte und Berechtigungen an Inhalten", paragraphs: ["Bearbeitungs-, OCR-, Übersetzungs-, Redraw-, Typesetting- und Veröffentlichungswerkzeuge verleihen keine Rechte an Werken Dritter. Sie sind allein dafür verantwortlich zu prüfen, ob die Nutzung der Inhalte in Ihrer Rechtsordnung zulässig ist und ob Sie über die erforderlichen Lizenzen, Genehmigungen, Einwilligungen oder sonstigen Rechtsgrundlagen verfügen."] },
        { title: "2. Community-Bereiche und Moderation", paragraphs: ["Beiträge, Profile, Anhänge, Bewerbungen und Meldungen, die in Community-Bereiche wie Scanlation Feed eingestellt werden, können durch automatisierte Systeme und menschliche Moderatoren geprüft werden. Wir können Inhalte ausblenden, kennzeichnen, entfernen, einschränken oder eskalieren, wenn sie irreführend, missbräuchlich, rechtswidrig, verletzend, unsicher oder mit der Integrität der Plattform unvereinbar erscheinen."], bullets: ["Veröffentlichen Sie kein Phishing, keine Malware, keinen Spam, keine Identitätsnachahmung und keine betrügerischen Rekrutierungsangebote.", "Legen Sie keine personenbezogenen Daten Dritter ohne Rechtsgrundlage offen.", "Nutzen Sie Community-Bereiche nicht zur Koordinierung von Missbrauch, Belästigung oder Rechtsverletzungen."] },
        { title: "3. Externe Veröffentlichung, KI-Anbieter und Integrationen", paragraphs: ["Wenn Sie Blogger, Imgur, Discord Webhook, KI-Anbieter, Uploads oder andere externe Konnektoren nutzen, weisen Sie KŌMA Studio an, die Dateien, Prompts, Ergebnisse, Metadaten und technischen Anweisungen zu übertragen, die für die gewünschte Aktion erforderlich sind. Es liegt in Ihrer Verantwortung, vor dem Start des Transfers zu prüfen, ob Ziel, Publikum und Berechtigungen angemessen sind."] },
        { title: "4. Bug Reports und Diagnostik", paragraphs: ["Bug-Report-Flows können den aktuellen Screenshot, Anhänge, ausgewählte Logs, Umgebungsdiagnosen, Kontokontext und technische Details enthalten, die uns bei der Untersuchung eines Problems helfen. Prüfen Sie sämtliches Material vor dem Absenden. Wenn der Flow Dienste wie Discord Webhook oder Imgur nutzt, wird das ausgewählte Material an diese Dienste zur Bearbeitung der Meldung übermittelt."] },
        { title: "5. Durchsetzungsmaßnahmen", paragraphs: ["Wir können den Zugriff auf Funktionen, Dateien, Integrationen oder Konten beschränken, aussetzen, entfernen oder beenden, wenn wir vernünftigerweise annehmen, dass dies zur Schadensvermeidung, Gesetzesbefolgung, Untersuchung von Missbrauch, Reaktion auf eine berechtigte Beschwerde, zum Schutz von Nutzern oder zur Wahrung der Integrität des Dienstes erforderlich ist. Wiederholte oder schwerwiegende Verstöße können zu dauerhaften Einschränkungen führen."] },
      ],
    },
  },
};
