import type { LegalContentBundle } from "./legalContent.types";

export const legalContentFr: LegalContentBundle = {
  releaseDate: "13 avril 2026",
  documents: {
    terms: {
      eyebrow: "Conditions d'utilisation",
      title: "Conditions d'utilisation de KŌMA Studio",
      summary: "Règles encadrant l'accès à KŌMA Studio, les intégrations optionnelles, les espaces communautaires et l'usage des fonctionnalités desktop et connectées au web.",
      highlights: ["KŌMA Studio combine une application desktop avec authentification web, mises à jour, support et services distants optionnels.", "Vous restez responsable des droits, autorisations et de la légalité des fichiers, prompts, liens et contenus que vous envoyez ou publiez.", "Les fonctionnalités, intégrations et contrôles de sécurité peuvent évoluer lorsque changent la loi, les prestataires ou les exigences de prévention des abus."],
      sections: [
        { title: "1. Portée du service", paragraphs: ["KŌMA Studio fournit des outils de nettoyage, redraw, OCR, traduction, lettrage, automatisation de workflow, publication assistée et autres fonctions de productivité pour la scanlation. Certaines fonctions tournent entièrement sur l'appareil ; d'autres dépendent d'une infrastructure distante pour le compte, le support, les mises à jour, les services managés ou les intégrations activées par l'utilisateur.", "Le service peut évoluer dans le temps. Nous pouvons ajouter, modifier, remplacer ou retirer des fonctionnalités, prestataires, catalogues de modèles, exigences de sécurité ou règles de compatibilité lorsque cela est nécessaire pour l'exploitation du produit, la conformité juridique ou l'intégrité de l'infrastructure."] },
        { title: "2. Compte, éligibilité et sécurité", paragraphs: ["Vous devez fournir des informations exactes lors de l'inscription, garder vos identifiants confidentiels et n'utiliser le service que si vous pouvez conclure un accord juridiquement contraignant selon la loi qui vous est applicable. Le service n'est pas destiné aux enfants n'ayant pas l'âge minimum requis par la loi applicable pour utiliser des services en ligne sans autorisation parentale ou du tuteur.", "Nous pouvons exiger une vérification d'email, la validation d'un appareil de confiance, un flux travel token, un CAPTCHA, des limites de débit, une mise à jour obligatoire de l'application, une revue de session, des restrictions temporaires et d'autres contrôles raisonnables pour protéger les comptes, les intégrations et la plateforme."], bullets: ["Vous êtes responsable de l'activité réalisée sur votre compte, sauf disposition légale contraire.", "Il est interdit de partager vos identifiants, de bypasser des restrictions techniques ou d'utiliser le service pour automatiser fraude ou abus.", "Nous pouvons suspendre ou résilier l'accès en cas de risque de sécurité, d'impayé, de conduite illicite ou de violation grave de ces documents."] },
        { title: "3. Contenu utilisateur, droits et usage acceptable", paragraphs: ["La propriété de votre contenu vous appartient. Toutefois, vous accordez à KŌMA Studio les droits limités nécessaires pour héberger, transmettre, mettre en cache, transformer, afficher ou traiter ce contenu uniquement afin d'exécuter les fonctionnalités demandées, de maintenir la sécurité et d'assurer le support.", "Vous déclarez disposer des droits, licences, autorisations et bases légales nécessaires pour envoyer, traiter, publier ou partager toute image, tout texte, prompt, log, pièce jointe ou lien utilisé dans le service. KŌMA Studio ne vous accorde aucun droit sur des œuvres de tiers et ne valide pas votre chaîne de droits."], bullets: ["N'utilisez pas le service pour violer le droit d'auteur, les marques, la vie privée, la confidentialité, les droits de la personnalité ou la sécurité de la plateforme.", "N'envoyez pas de malware, phishing, contenu illicite, recrutement trompeur ou contenu communautaire abusif.", "Nous pouvons supprimer, masquer, bloquer ou signaler un contenu qui crée un risque juridique, de sécurité, réputationnel ou opérationnel."] },
        { title: "4. Services tiers et intégrations", paragraphs: ["Des fonctionnalités comme Blogger, Imgur, Discord webhook, les fournisseurs d'IA en BYOK et autres connecteurs ne fonctionnent que si vous les activez délibérément. Lorsque vous lancez ces flux, KŌMA Studio peut transmettre le contenu sélectionné, les identifiants, les métadonnées et les instructions d'exécution nécessaires à l'action demandée.", "Les services tiers fonctionnent selon leurs propres conditions, politiques de confidentialité, règles de conservation, limites et engagements de disponibilité. Nous ne sommes pas responsables d'une indisponibilité, d'un changement de politique, d'un blocage de compte, du traitement des données ou d'un préjudice causé par des prestataires que vous avez choisi de connecter ou par des identifiants configurés par vous." ] },
        { title: "5. Disponibilité, responsabilité et mises à jour", paragraphs: ["Le service est fourni sur une base de disponibilité et de mise à jour continue. Dans la mesure maximale permise par la loi, KŌMA Studio n'est pas responsable des dommages indirects, pertes de profits, retards éditoriaux, échecs de publication externe, indisponibilités de prestataires ou préjudices causés par un usage illicite ou non autorisé du service par l'utilisateur.", "Rien dans ces conditions n'exclut les droits impératifs du consommateur ou de la vie privée. Nous pouvons mettre à jour ces conditions et les mentions associées lorsque changent le produit, la loi, les prestataires ou le profil de risque. La version en vigueur est publiée dans le Centre juridique et une nouvelle acceptation peut être requise pour poursuivre l'utilisation du service."] },
      ],
    },
    privacy: {
      eyebrow: "Politique de confidentialité",
      title: "Politique de confidentialité de KŌMA Studio",
      summary: "Comment KŌMA Studio collecte, utilise, partage, conserve et protège les données personnelles liées aux comptes, au support, à la sécurité, aux intégrations et aux fonctionnalités communautaires.",
      highlights: ["KŌMA Studio agit comme responsable du traitement pour les opérations décrites ici, sauf lorsqu'un tiers agit pour son propre compte comme responsable indépendant.", "Nous traitons des données de compte, d'appareil, de support, de modération et d'intégration afin d'exploiter le service, protéger les utilisateurs et respecter nos obligations légales.", "Nous n'utilisons pas de cookies publicitaires dans le produit actuel et nous ne vendons pas de données personnelles."],
      sections: [
        { title: "1. Champ d'application et rôle de responsable", paragraphs: ["Cette politique s'applique à l'application desktop de KŌMA Studio, aux flux web d'authentification, aux opérations de support, aux flux de bug report, aux espaces communautaires et aux services connectés. Pour les traitements décrits ici, KŌMA Studio agit comme responsable du traitement, sauf lorsqu'un autre prestataire détermine de manière autonome les finalités et les moyens du traitement.", "Les prestataires d'email, d'IA connectée par vous, les plateformes externes de publication et les partenaires d'infrastructure peuvent agir comme sous-traitants ou responsables indépendants selon l'activité. Leurs propres documents juridiques s'appliquent également aux données qu'ils traitent pour leur propre compte."] },
        { title: "2. Catégories de données personnelles", paragraphs: ["Nous pouvons collecter des données d'inscription et de compte, telles que le nom affiché, l'adresse email, le statut de vérification, les identifiants de compte, les journaux de session, les tentatives de connexion, les identifiants d'appareil de confiance, les signaux IP liés à la sécurité et les diagnostics de la machine ou de l'application nécessaires pour sécuriser l'accès et exploiter le service.", "Nous pouvons aussi traiter les demandes de support et bug reports, les publications communautaires et historiques de modération, les paramètres d'intégration, les destinations de webhook, les identifiants de prestataires ainsi que les fichiers, captures, prompts, logs, pièces jointes ou métadonnées que vous choisissez d'envoyer via le produit."] },
        { title: "3. Finalités et bases légales", paragraphs: ["Nous traitons les données personnelles pour créer et administrer les comptes, authentifier les sessions, livrer les mises à jour, répondre au support, enquêter sur les bugs, exploiter les espaces communautaires, prévenir les abus, protéger l'infrastructure, respecter les obligations légales, faire appliquer nos conditions et résoudre les incidents de sécurité.", "Selon le contexte, les principales bases légales sont l'exécution du contrat, l'intérêt légitime pour la sécurité et la fiabilité du service, le respect d'une obligation légale ainsi que le consentement ou l'action affirmative de l'utilisateur pour des fonctionnalités optionnelles telles que les bug reports, les intégrations volontaires, les connexions BYOK ou les communications optionnelles. Si vous vous trouvez dans l'Espace économique européen, au Royaume-Uni, au Brésil ou dans une juridiction similaire, vous pouvez bénéficier de droits légaux supplémentaires décrits ci-dessous."] },
        { title: "4. Partage, transferts internationaux et tiers", paragraphs: ["Nous partageons des données personnelles uniquement lorsque cela est nécessaire pour exploiter le service, exécuter vos instructions, respecter une obligation légale, prévenir la fraude ou défendre des droits. Les destinataires habituels peuvent inclure des fournisseurs d'hébergement et de base de données, des fournisseurs d'email transactionnel, des outils de support, des intégrations optionnelles comme Blogger, Imgur, Discord webhook et des services d'IA que vous connectez.", "Comme ces prestataires peuvent opérer dans différents pays, les données personnelles peuvent être transférées à l'international. Lorsque cela est requis, nous adoptons des garanties contractuelles, organisationnelles et techniques adaptées au transfert et au risque, tout en reconnaissant que certains prestataires traitent les données selon leurs propres cadres juridiques et politiques."] },
        { title: "5. Conservation, sécurité et mineurs", paragraphs: ["Nous conservons les données personnelles uniquement pendant la durée nécessaire aux finalités décrites dans cette politique, notamment la fourniture du service, la prévention de la fraude, la surveillance de sécurité, l'analyse d'incidents, la défense juridique et la conformité réglementaire. Différentes catégories peuvent avoir des durées différentes et certains enregistrements ne peuvent pas être supprimés immédiatement lorsque la loi impose leur conservation.", "Nous utilisons des mesures telles que le hashage des mots de passe, les contrôles de session, les jetons de courte durée, la validation des webhooks, les journaux d'audit, les limites de débit, les contrôles d'accès et les revues de sécurité pour réduire les accès non autorisés ou les abus. Aucun système n'est totalement sûr ; vous devez donc éviter d'envoyer des données sensibles inutiles. Le service n'est pas destiné aux enfants en dessous de l'âge numérique minimum applicable."] },
        { title: "6. Vos droits et contact", paragraphs: ["Sous réserve de la loi applicable, vous pouvez demander l'accès, la confirmation du traitement, la rectification, la portabilité lorsque disponible, l'effacement, l'anonymisation, l'opposition, la limitation, le retrait du consentement lorsque celui-ci est la base, ainsi que des informations sur les destinataires, la conservation, les garanties et les décisions automatisées. Nous pouvons demander une vérification raisonnable d'identité avant de traiter une demande et conserver un enregistrement minimal de la demande et de notre réponse à des fins de responsabilité.", "Les demandes relatives à la confidentialité, aux données personnelles, aux cookies ou aux mentions légales doivent être envoyées via le canal officiel de support à l'adresse {supportUrl}. Nous nous efforçons de répondre dans les délais exigés par la législation applicable, y compris le délai d'un mois du GDPR lorsqu'il s'applique."] },
      ],
    },
    cookies: {
      eyebrow: "Politique de cookies",
      title: "Politique de cookies de KŌMA Studio",
      summary: "Comment KŌMA Studio utilise les cookies, le stockage local et les technologies associées pour l'authentification, la sécurité et le fonctionnement du produit.",
      highlights: ["Le produit actuel repose principalement sur des cookies strictement nécessaires et du stockage local indispensables pour authentifier les utilisateurs et maintenir la sécurité.", "L'application desktop conserve également une partie des données localement via Electron et le stockage de l'application, et pas uniquement via les cookies du navigateur.", "Si KŌMA Studio introduit de l'analytics, de la publicité ou de la personnalisation fondés sur des cookies non strictement nécessaires, cette politique et les contrôles associés seront mis à jour avant que cet usage ne devienne standard."],
      sections: [
        { title: "1. Technologies utilisées", paragraphs: ["KŌMA Studio peut utiliser des cookies HttpOnly, des cookies de session, le stockage du navigateur, le stockage de l'application desktop, des préférences d'email mémorisé, des identifiants d'appareil et des technologies équivalentes pour maintenir la connexion, sécuriser les sessions, mémoriser l'état du produit et prendre en charge les flux d'authentification, de récupération et de mise à jour."] },
        { title: "2. Cookies strictement nécessaires", paragraphs: ["Les cookies strictement nécessaires sont utilisés pour l'authentification, la continuité de session, la prévention de la fraude, la détection d'abus, la récupération de compte, les vérifications de sécurité et l'accès aux zones protégées. Ces technologies sont nécessaires pour fournir le service demandé par l'utilisateur et ne sont pas utilisées à des fins publicitaires dans le produit actuel."], bullets: ["Établissement de la session et expiration contrôlée.", "Vérifications de sécurité et anti-abus pendant la connexion et la récupération de compte.", "Continuité d'accès lorsqu'un état protégé du compte doit être maintenu."] },
        { title: "3. Stockage local et persistance desktop", paragraphs: ["KŌMA Studio peut enregistrer localement des préférences non sensibles, comme l'état de l'interface, la langue sélectionnée, l'email mémorisé, les presets, le choix du canal de mise à jour ou des réglages de confort liés au workflow. Les paramètres d'intégration ou jetons peuvent également être stockés localement lorsque la fonctionnalité l'exige et que le produit est conçu pour conserver ces informations sur l'appareil lorsque cela est possible."] },
        { title: "4. Gestion de ces technologies", paragraphs: ["Vous pouvez effacer les cookies et le stockage local depuis votre navigateur ou vous déconnecter et réinitialiser l'état local depuis l'application lorsque cette option est disponible. Bloquer ou supprimer des technologies strictement nécessaires peut empêcher la connexion, la récupération de compte ou le fonctionnement normal des zones protégées du produit."] },
      ],
    },
    content: {
      eyebrow: "Politique d'usage et de contenu",
      title: "Politique d'usage et de contenu de KŌMA Studio",
      summary: "Règles relatives aux fichiers envoyés, au contenu communautaire, aux bug reports, à la publication externe, à la modération et à l'usage licite des fonctionnalités de KŌMA Studio.",
      highlights: ["Vous ne pouvez traiter ou publier du contenu que si vous disposez des droits ou d'une autorisation légale pour le faire.", "Les fonctionnalités communautaires et de publication peuvent être modérées, restreintes ou supprimées lorsqu'elles créent un risque juridique, un abus ou un risque de sécurité.", "Les bug reports et les intégrations optionnelles peuvent envoyer des captures, logs, pièces jointes ou fichiers sélectionnés à des services tiers lorsque vous activez ces flux."],
      sections: [
        { title: "1. Droits et autorisations sur le contenu", paragraphs: ["Les outils d'édition, OCR, traduction, redraw, lettrage et publication ne vous accordent aucun droit sur des œuvres de tiers. Vous êtes seul responsable de vérifier si l'usage du contenu est licite dans votre juridiction et de disposer des licences, autorisations, consentements ou autre base légale nécessaires à cet usage."] },
        { title: "2. Espaces communautaires et modération", paragraphs: ["Les publications, profils, pièces jointes, candidatures et signalements envoyés dans des espaces communautaires comme Scanlation Feed peuvent être examinés par des systèmes automatisés et des modérateurs humains. Nous pouvons masquer, étiqueter, supprimer, restreindre ou escalader un contenu qui paraît trompeur, abusif, illicite, contrefaisant, dangereux ou incompatible avec l'intégrité de la plateforme."], bullets: ["Ne publiez pas de phishing, malware, spam, usurpation d'identité ou offres de recrutement frauduleuses.", "N'exposez pas de données personnelles de tiers sans base légale.", "N'utilisez pas les espaces communautaires pour coordonner des abus, du harcèlement ou des atteintes." ] },
        { title: "3. Publication externe, fournisseurs IA et intégrations", paragraphs: ["Lorsque vous utilisez Blogger, Imgur, Discord webhook, des fournisseurs IA, des téléversements ou d'autres connecteurs externes, vous demandez à KŌMA Studio de transmettre les fichiers, prompts, résultats, métadonnées et instructions techniques nécessaires à l'action. Il vous appartient de vérifier que la destination, le public et les permissions sont appropriés avant de lancer le transfert."] },
        { title: "4. Bug reports et diagnostics", paragraphs: ["Les flux de bug report peuvent inclure la capture d'écran actuelle, des pièces jointes, des logs sélectionnés, des diagnostics d'environnement, le contexte du compte et des détails techniques nous aidant à enquêter sur le problème. Revoyez tout le matériel avant l'envoi. Lorsque le flux utilise des services comme Discord webhook ou Imgur, le matériel sélectionné est envoyé à ces services pour traiter le signalement."] },
        { title: "5. Mesures d'application", paragraphs: ["Nous pouvons limiter, suspendre, supprimer ou résilier l'accès à toute fonctionnalité, fichier, intégration ou compte lorsque nous estimons raisonnablement que cela est nécessaire pour éviter un dommage, respecter la loi, enquêter sur un abus, répondre à un signalement valable, protéger les utilisateurs ou préserver l'intégrité du service. Les violations répétées ou graves peuvent conduire à des restrictions permanentes."] },
      ],
    },
  },
};
