import type { LegalContentBundle } from "./legalContent.types";

export const legalContentHi: LegalContentBundle = {
  releaseDate: "13 अप्रैल 2026",
  documents: {
    terms: {
      eyebrow: "सेवा की शर्तें",
      title: "KŌMA Studio सेवा की शर्तें",
      summary: "KŌMA Studio की पहुंच, वैकल्पिक इंटीग्रेशन, कम्युनिटी क्षेत्रों और डेस्कटॉप तथा वेब-समर्थित सुविधाओं के उपयोग को नियंत्रित करने वाले नियम।",
      highlights: [
        "KŌMA Studio डेस्कटॉप ऐप, वेब प्रमाणीकरण, अपडेट, सपोर्ट और वैकल्पिक रिमोट सेवाओं को एक साथ जोड़ता है।",
        "आप जिन फ़ाइलों, prompts, links और materials को भेजते या प्रकाशित करते हैं, उनके अधिकार, अनुमति और वैधता के लिए आप स्वयं जिम्मेदार रहते हैं।",
        "फीचर्स, integrations और security controls समय-समय पर कानूनों, providers या abuse-prevention आवश्यकताओं के अनुसार बदल सकते हैं।",
      ],
      sections: [
        { title: "1. सेवा का दायरा", paragraphs: ["KŌMA Studio cleaning, redraw, OCR, translation, typesetting, workflow automation, assisted publishing और scanlation productivity के अन्य टूल प्रदान करता है। कुछ फीचर पूरी तरह डिवाइस पर चलते हैं, जबकि अन्य account, support, updates, managed services या user-enabled integrations के लिए remote infrastructure पर निर्भर करते हैं।", "सेवा समय के साथ बदल सकती है। उत्पाद संचालन, कानूनी अनुपालन या infrastructure integrity के लिए हम features, providers, model catalogs, security requirements या compatibility rules को जोड़, बदल, replace या retire कर सकते हैं।"] },
        { title: "2. खाता, पात्रता और सुरक्षा", paragraphs: ["आपको सही registration जानकारी देनी होगी, अपने credentials गोपनीय रखने होंगे और सेवा का उपयोग केवल तब करना होगा जब आप लागू कानून के अनुसार बाध्यकारी समझौता करने के योग्य हों। यह सेवा उन बच्चों के लिए नहीं है जो ऑनलाइन सेवाओं के उपयोग के लिए लागू न्यूनतम कानूनी आयु से कम हैं और जिनके पास अभिभावकीय अनुमति नहीं है।", "हम email verification, trusted device validation, travel token flow, CAPTCHA, rate limits, mandatory app updates, session review, temporary restrictions और अन्य reasonable controls लागू कर सकते हैं ताकि accounts, integrations और platform सुरक्षित रहें।"], bullets: ["कानून अन्यथा न कहे तो आपके खाते पर होने वाली गतिविधि के लिए आप जिम्मेदार हैं।", "credentials साझा करना, technical restrictions को bypass करना, या सेवा का उपयोग fraud या abuse automate करने के लिए करना प्रतिबंधित है।", "यदि security risk, unlawful conduct या इन दस्तावेज़ों का गंभीर उल्लंघन पाया जाता है, तो हम access suspend या terminate कर सकते हैं।"] },
        { title: "3. उपयोगकर्ता सामग्री, अधिकार और स्वीकार्य उपयोग", paragraphs: ["आपकी सामग्री का स्वामित्व आपका ही रहता है। हालांकि, आप KŌMA Studio को सीमित अधिकार देते हैं ताकि वह केवल requested features चलाने, सुरक्षा बनाए रखने और support देने के लिए उस सामग्री को host, transmit, cache, transform, display या process कर सके।", "आप यह घोषित करते हैं कि सेवा में उपयोग की गई किसी भी image, text, prompt, log, attachment या link को भेजने, process करने, publish करने या share करने के लिए आपके पास आवश्यक rights, licenses, permissions और lawful basis हैं। KŌMA Studio आपको third-party works पर कोई अधिकार नहीं देता और आपकी chain of title validate नहीं करता।"], bullets: ["सेवा का उपयोग copyright, trademark, privacy, confidentiality, personality rights या platform security का उल्लंघन करने के लिए न करें।", "malware, phishing, illegal material, misleading recruitment या abusive community content अपलोड न करें।", "कानूनी, सुरक्षा, प्रतिष्ठात्मक या परिचालन जोखिम पैदा करने वाली सामग्री को हम remove, hide, block या report कर सकते हैं।"] },
        { title: "4. तृतीय-पक्ष सेवाएं और इंटीग्रेशन", paragraphs: ["Blogger, Imgur, Discord webhook, BYOK AI providers और अन्य connectors जैसी सुविधाएं तभी चलती हैं जब आप उन्हें जानबूझकर enable करते हैं। इन flows को trigger करने पर KŌMA Studio requested action पूरी करने के लिए selected content, credentials, metadata और technical instructions भेज सकता है।", "तृतीय-पक्ष सेवाएं अपनी terms, privacy notices, retention rules, limits और availability commitments के अनुसार चलती हैं। जिन providers को आपने जोड़ा है या जिन credentials को आपने configure किया है, उनके कारण होने वाले downtime, policy changes, account restrictions, data handling या losses के लिए हम जिम्मेदार नहीं हैं।"] },
        { title: "5. उपलब्धता, उत्तरदायित्व और अपडेट", paragraphs: ["सेवा availability और ongoing updates के आधार पर प्रदान की जाती है। लागू कानून द्वारा अनुमत अधिकतम सीमा तक KŌMA Studio अप्रत्यक्ष हानि, लाभ के नुकसान, editorial delays, external publishing failure, provider outages या उपयोगकर्ता द्वारा सेवा के unlawful या unauthorized use से होने वाले नुकसान के लिए उत्तरदायी नहीं है।", "इन शर्तों में कुछ भी non-waivable consumer या privacy rights को बाहर नहीं करता। जब product, law, providers या risk profile बदलते हैं, हम इन terms और संबंधित legal notices को update कर सकते हैं। वर्तमान version Legal Center में प्रकाशित रहती है और continued use के लिए renewed acceptance की आवश्यकता हो सकती है।"] },
      ],
    },
    privacy: {
      eyebrow: "गोपनीयता नीति",
      title: "KŌMA Studio गोपनीयता नीति",
      summary: "KŌMA Studio account, support, security, integrations और community features से जुड़े personal data को कैसे collect, use, share, retain और protect करता है।",
      highlights: [
        "यहां वर्णित processing के लिए KŌMA Studio सामान्यतः controller की भूमिका निभाता है, सिवाय उन मामलों के जहां कोई third party अपने उद्देश्यों के लिए independent controller के रूप में कार्य करती है।",
        "हम account, device, support, moderation और integration data को service चलाने, users की रक्षा करने और legal obligations पूरी करने के लिए process करते हैं।",
        "हम वर्तमान product में advertising cookies का उपयोग नहीं करते और personal data को sell नहीं करते।",
      ],
      sections: [
        { title: "1. दायरा और controller की भूमिका", paragraphs: ["यह नीति KŌMA Studio desktop app, web authentication flows, support operations, bug report flows, community areas और connected services पर लागू होती है। यहां वर्णित processing के लिए KŌMA Studio controller के रूप में कार्य करता है, जब तक कि कोई अन्य provider processing के purposes और means स्वयं निर्धारित न करे।", "email providers, आपके द्वारा जोड़े गए AI services, external publishing platforms और infrastructure partners activity के अनुसार processors या independent controllers के रूप में कार्य कर सकते हैं। उनके अपने legal documents उनके द्वारा अपने behalf पर process किए गए data पर भी लागू होते हैं।"] },
        { title: "2. व्यक्तिगत डेटा की श्रेणियां", paragraphs: ["हम registration और account data जैसे display name, email, verification status, account identifiers, session records, login attempts, trusted-device identifiers, security-related IP signals और access protection तथा service operation के लिए आवश्यक machine या app diagnostics collect कर सकते हैं।", "हम support submissions और bug reports, community posts और moderation history, integration settings, webhook destinations, provider identifiers और वे files, screenshots, prompts, logs, attachments या metadata भी process कर सकते हैं जिन्हें आप product के माध्यम से भेजते हैं।"] },
        { title: "3. उद्देश्य और कानूनी आधार", paragraphs: ["हम personal data को accounts बनाने और administer करने, sessions authenticate करने, updates deliver करने, support requests का जवाब देने, bugs की जांच करने, community areas चलाने, abuse रोकने, infrastructure की रक्षा करने, legal obligations पूरी करने, terms enforce करने और security incidents को resolve करने के लिए process करते हैं।", "संदर्भ के अनुसार मुख्य legal bases contract performance, service security और reliability में legitimate interests, legal obligations का पालन, और optional features जैसे bug reports, voluntary integrations, BYOK connections या optional communications के लिए consent या affirmative user action हैं। यदि आप EEA, UK, Brazil या समान jurisdiction में हैं, तो आपको नीचे वर्णित अतिरिक्त statutory rights प्राप्त हो सकते हैं।"] },
        { title: "4. साझा करना, अंतरराष्ट्रीय ट्रांसफर और तृतीय पक्ष", paragraphs: ["हम personal data को केवल तब share करते हैं जब यह service चलाने, आपके instructions execute करने, law comply करने, fraud prevent करने या rights defend करने के लिए आवश्यक हो। Typical recipients में hosting और database providers, transactional email providers, support tools, Blogger, Imgur, Discord webhook जैसी optional integrations और आपके द्वारा connected AI services शामिल हो सकते हैं।", "चूंकि ये providers अलग-अलग देशों में operate कर सकते हैं, personal data का international transfer हो सकता है। आवश्यकता पड़ने पर हम transfer और risk के अनुरूप contractual, organizational और technical safeguards अपनाते हैं, जबकि यह मानते हुए कि कुछ providers अपने legal frameworks और policies के तहत data process करेंगे।"] },
        { title: "5. retention, security और minors", paragraphs: ["हम personal data को केवल उतनी अवधि तक retain करते हैं जितनी इस नीति में बताई गई purposes के लिए आवश्यक है, जिसमें service delivery, fraud prevention, security monitoring, incident analysis, legal defense और regulatory compliance शामिल हैं। अलग-अलग categories के retention periods अलग हो सकते हैं और कुछ records को कानून की मांग पर तुरंत delete नहीं किया जा सकता।", "हम password hashing, session controls, short-lived tokens, webhook validation, audit logs, rate limits, access controls और security reviews जैसी measures का उपयोग करते हैं ताकि unauthorized access या abuse का risk कम हो। कोई भी system पूर्णतः secure नहीं है, इसलिए अनावश्यक sensitive data भेजने से बचें। यह सेवा लागू digital age of consent से कम आयु के बच्चों के लिए नहीं है।"] },
        { title: "6. आपके अधिकार और संपर्क", paragraphs: ["लागू कानून के अधीन आप access, processing confirmation, correction, जहां उपलब्ध हो data portability, deletion, anonymization, objection, restriction, consent withdrawal (जहां वही basis हो) और recipients, retention, safeguards तथा automated decision-making के बारे में जानकारी का अनुरोध कर सकते हैं। अनुरोध पर कार्रवाई से पहले हम reasonable identity verification मांग सकते हैं और accountability उद्देश्यों के लिए request और response का न्यूनतम record रख सकते हैं।", "privacy, personal data, cookies या legal notices से संबंधित requests आधिकारिक support channel {supportUrl} के माध्यम से भेजी जानी चाहिए। हम लागू कानून द्वारा अपेक्षित समयसीमा के भीतर, और जहां लागू हो GDPR की one-month reference period के भीतर, उत्तर देने का प्रयास करते हैं।"] },
      ],
    },
    cookies: {
      eyebrow: "कुकी नीति",
      title: "KŌMA Studio कुकी नीति",
      summary: "KŌMA Studio authentication, security और product operation के लिए cookies, local storage और संबंधित technologies का उपयोग कैसे करता है।",
      highlights: [
        "वर्तमान product मुख्यतः strictly necessary cookies और local storage पर निर्भर है, जो users को authenticate करने और security बनाए रखने के लिए जरूरी हैं।",
        "desktop application Electron और app storage के माध्यम से भी कुछ data locally रखती है, केवल browser cookies के माध्यम से नहीं।",
        "यदि KŌMA Studio future में analytics, advertising या non-essential cookie-based personalization जोड़ता है, तो उस उपयोग के सामान्य होने से पहले यह नीति और संबंधित controls अपडेट किए जाएंगे।",
      ],
      sections: [
        { title: "1. उपयोग की जाने वाली technologies", paragraphs: ["KŌMA Studio HttpOnly cookies, session cookies, browser storage, desktop app storage, remembered-email preferences, device identifiers और समान technologies का उपयोग कर सकता है ताकि login बनाए रखा जा सके, sessions सुरक्षित रखे जा सकें, product state याद रखी जा सके और authentication, recovery तथा update flows को support दिया जा सके।"] },
        { title: "2. strictly necessary cookies", paragraphs: ["strictly necessary cookies का उपयोग authentication, session continuity, fraud prevention, abuse detection, account recovery, security checks और protected areas तक पहुंच के लिए किया जाता है। ये technologies user-requested service देने के लिए आवश्यक हैं और वर्तमान product में advertising के लिए उपयोग नहीं की जातीं।"], bullets: ["session establishment और controlled expiration।", "login और account recovery के दौरान security तथा anti-abuse verification।", "जब protected account state बनाए रखना आवश्यक हो, तब access continuity।"] },
        { title: "3. local storage और desktop persistence", paragraphs: ["KŌMA Studio non-sensitive preferences को locally store कर सकता है, जैसे interface state, selected language, remembered email, presets, update channel choice या workflow convenience settings। integration settings या tokens भी locally store किए जा सकते हैं जब feature को इसकी आवश्यकता हो और product इस information को यथासंभव device पर रखने के लिए designed हो।"] },
        { title: "4. इन technologies को कैसे manage करें", paragraphs: ["आप browser settings के माध्यम से cookies और local storage clear कर सकते हैं, या app में उपलब्ध होने पर sign out करके local state reset कर सकते हैं। strictly necessary technologies को block या delete करने से login, account recovery या protected areas के सामान्य संचालन में बाधा आ सकती है।"] },
      ],
    },
    content: {
      eyebrow: "उपयोग और सामग्री नीति",
      title: "KŌMA Studio उपयोग और सामग्री नीति",
      summary: "uploaded files, community content, bug reports, external publishing, moderation और KŌMA Studio features के lawful use के लिए नियम।",
      highlights: [
        "आप केवल वही सामग्री process या publish कर सकते हैं जिसके लिए आपके पास आवश्यक अधिकार या कानूनी अनुमति हो।",
        "community और publishing features को legal risk, abuse या security risk होने पर moderate, restrict या remove किया जा सकता है।",
        "bug reports और optional integrations, जब आप उन flows को trigger करते हैं, screenshots, logs, attachments या selected files को third-party services तक भेज सकते हैं।",
      ],
      sections: [
        { title: "1. सामग्री पर अधिकार और अनुमति", paragraphs: ["editing, OCR, translation, redraw, typesetting और publishing tools आपको third-party works पर कोई अधिकार नहीं देते। यह सुनिश्चित करने की जिम्मेदारी केवल आपकी है कि सामग्री का उपयोग आपके jurisdiction में lawful है और आपके पास आवश्यक licenses, permissions, consents या अन्य legal basis मौजूद हैं।"] },
        { title: "2. community areas और moderation", paragraphs: ["Scanlation Feed जैसे community spaces में भेजे गए posts, profiles, attachments, applications और reports का automated systems और human moderators द्वारा review किया जा सकता है। जो content misleading, abusive, unlawful, infringing, unsafe या platform integrity के विपरीत प्रतीत हो, उसे हम hide, label, remove, restrict या escalate कर सकते हैं।"], bullets: ["phishing, malware, spam, impersonation या fraudulent recruitment offers प्रकाशित न करें।", "बिना lawful basis के third-party personal data उजागर न करें।", "community areas का उपयोग abuse, harassment या infringement coordinate करने के लिए न करें।"] },
        { title: "3. external publishing, AI providers और integrations", paragraphs: ["जब आप Blogger, Imgur, Discord webhook, AI providers, uploads या अन्य external connectors का उपयोग करते हैं, तो आप KŌMA Studio को requested action पूरा करने के लिए files, prompts, outputs, metadata और technical instructions transmit करने का निर्देश देते हैं। transfer शुरू करने से पहले यह सुनिश्चित करना कि destination, audience और permissions उपयुक्त हैं, आपकी जिम्मेदारी है।"] },
        { title: "4. bug reports और diagnostics", paragraphs: ["bug report flows में वर्तमान screenshot, attachments, selected logs, environment diagnostics, account context और technical details शामिल हो सकती हैं जो समस्या की जांच में हमारी मदद करें। submit करने से पहले सामग्री की समीक्षा करें। यदि flow Discord webhook या Imgur जैसी services का उपयोग करता है, तो selected material report processing के लिए उन services को भेजा जाएगा।"] },
        { title: "5. enforcement measures", paragraphs: ["यदि हमें उचित रूप से लगता है कि हानि रोकने, कानून का पालन करने, abuse की जांच करने, वैध शिकायत का जवाब देने, users की सुरक्षा करने या service integrity बनाए रखने के लिए आवश्यक है, तो हम किसी भी feature, file, integration या account तक पहुंच को limit, suspend, remove या terminate कर सकते हैं। repeated या severe violations स्थायी restrictions का कारण बन सकती हैं।"] },
      ],
    },
  },
};
