import type { FreeAiProviderCatalogEntry } from "./freeAiProviderCatalog";
import {
  LAST_VERIFIED_AT,
  createOcrStage,
  createTranslationStage,
} from "./freeAiProviderCatalogBuilders";

export const FREE_AI_PROVIDER_CATALOG_EXTENDED: FreeAiProviderCatalogEntry[] = [
  {
      id: "cloudflare_workers_ai",
      name: "Cloudflare Workers AI",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://developers.cloudflare.com/workers-ai/",
      setupUrl: "https://developers.cloudflare.com/workers-ai/get-started/rest-api/",
      limitsUrl: "https://developers.cloudflare.com/workers-ai/platform/pricing/",
      rateLimitsUrl: "https://developers.cloudflare.com/workers-ai/platform/limits/",
      setupSummary: "Requires a Cloudflare account with a token/API and an account id for the REST API.",
      limitsSummary: "Plano free inclui 10.000 neurons/dia.",
      rateLimitSummary: "Limites de throughput e requests variam conforme plano e modelo.",
      stages: {
        translation: createTranslationStage(
          "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
          "@cf/openai/gpt-oss-20b",
          [
            {
              id: "cloudflare-cf-aisingapore-gemma-sea-lion-v4-27b-it",
              label: "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
              apiModel: "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
            },
            {
              id: "cloudflare-cf-ibm-granite-granite-4-0-h-micro",
              label: "@cf/ibm-granite/granite-4.0-h-micro",
              apiModel: "@cf/ibm-granite/granite-4.0-h-micro",
            },
            { id: "cloudflare-cf-openai-gpt-oss-120b", label: "@cf/openai/gpt-oss-120b", apiModel: "@cf/openai/gpt-oss-120b" },
            { id: "cloudflare-cf-openai-gpt-oss-20b", label: "@cf/openai/gpt-oss-20b", apiModel: "@cf/openai/gpt-oss-20b" },
            { id: "cloudflare-cf-qwen-qwen3-30b-a3b-fp8", label: "@cf/qwen/qwen3-30b-a3b-fp8", apiModel: "@cf/qwen/qwen3-30b-a3b-fp8" },
            { id: "cloudflare-cf-zai-org-glm-4-7-flash", label: "@cf/zai-org/glm-4.7-flash", apiModel: "@cf/zai-org/glm-4.7-flash" },
            {
              id: "cloudflare-cf-deepseek-r1-distill-qwen-32b",
              label: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
              apiModel: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
            },
            {
              id: "cloudflare-mistral-small-3-1-24b-instruct",
              label: "@cf/mistralai/mistral-small-3.1-24b-instruct",
              apiModel: "@cf/mistralai/mistral-small-3.1-24b-instruct",
            },
            {
              id: "cloudflare-cf-llama-4-scout-instruct",
              label: "@cf/meta/llama-4-scout-17b-16e-instruct",
              apiModel: "@cf/meta/llama-4-scout-17b-16e-instruct",
            },
            {
              id: "cloudflare-cf-llama-3-3-70b-instruct-fp8-fast",
              label: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
              apiModel: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
            },
            {
              id: "cloudflare-cf-llama-3-1-8b-instruct-fast",
              label: "@cf/meta/llama-3.1-8b-instruct-fast",
              apiModel: "@cf/meta/llama-3.1-8b-instruct-fast",
            },
            ],
          true,
          {
            configFields: [
              {
                id: "account_id",
                label: "Cloudflare Account ID",
                placeholder: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                required: true,
                description: "Found in the Cloudflare dashboard under Workers AI.",
              },
            ],
          },
        ),
        ocr: createOcrStage(
          "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
          "@cf/meta/llama-3.2-11b-vision-instruct",
          [
            {
              id: "cf-llama-vision-11b",
              label: "Llama 3.2 11B Vision",
              apiModel: "@cf/meta/llama-3.2-11b-vision-instruct",
            },
            {
              id: "cloudflare-cf-llama-4-scout-vision",
              label: "@cf/meta/llama-4-scout-17b-16e-instruct",
              apiModel: "@cf/meta/llama-4-scout-17b-16e-instruct",
            },
            ],
          true,
          {
            configFields: [
              {
                id: "account_id",
                label: "Cloudflare Account ID",
                placeholder: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                required: true,
                description: "Found in the Cloudflare dashboard under Workers AI.",
              },
            ],
          },
        ),
      },
    },
  {
      id: "zhipu_ai",
      name: "Zhipu AI",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://open.bigmodel.cn/",
      setupUrl: "https://open.bigmodel.cn/usercenter/apikeys",
      limitsUrl: "https://open.bigmodel.cn/",
      rateLimitsUrl: "https://open.bigmodel.cn/",
      setupSummary: "Crie uma API key na plataforma BigModel/Zhipu e use o endpoint OpenAI-compatible oficial.",
      limitsSummary: "A free tier exists, but the platform does not publish a consolidated limits table.",
      rateLimitSummary: "Rate limits are not documented in a consolidated way for the free tier.",
      stages: {
        translation: createTranslationStage("https://open.bigmodel.cn/api/paas/v4", "glm-4-flash", [
          { id: "zhipu-glm-4-flash", label: "GLM-4-Flash", apiModel: "glm-4-flash" },
          { id: "zhipu-glm-4.5-flash", label: "GLM-4.5-Flash", apiModel: "glm-4.5-flash" },
          { id: "zhipu-glm-4.7-flash", label: "GLM-4.7-Flash", apiModel: "glm-4.7-flash" },
        ]),
        ocr: createOcrStage("https://open.bigmodel.cn/api/paas/v4", "glm-4.6v-flash", [
          { id: "zhipu-glm-4.6v-flash", label: "GLM-4.6V-Flash", apiModel: "glm-4.6v-flash" },
        ]),
      },
    },
  {
      id: "llm7_io",
      name: "LLM7.io",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://llm7.io/",
      setupUrl: "https://token.llm7.io",
      limitsUrl: "https://llm7.io/",
      rateLimitsUrl: "https://llm7.io/",
      setupSummary: "Generate a token in the LLM7.io dashboard and use the official OpenAI-compatible endpoint.",
      limitsSummary: "The free plan is reported at 30 RPM; some accounts reach 120 RPM with their own token.",
      rateLimitSummary: "30 RPM on the basic tier; can rise to 120 RPM depending on the token/account.",
      stages: {
        translation: createTranslationStage("https://api.llm7.io/v1", "deepseek-r1", [
          { id: "llm7-deepseek-r1", label: "deepseek-r1", apiModel: "deepseek-r1" },
        ]),
      },
    },
  {
      id: "kluster_ai",
      name: "Kluster AI",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://platform.kluster.ai/",
      setupUrl: "https://platform.kluster.ai/apikeys",
      limitsUrl: "https://platform.kluster.ai/",
      rateLimitsUrl: "https://platform.kluster.ai/",
      setupSummary: "Crie uma API key na plataforma Kluster AI e use o endpoint OpenAI-compatible oficial.",
      limitsSummary: "The provider offers a free tier but does not publish a consolidated limits table.",
      rateLimitSummary: "Rate limits are not documented in a consolidated form.",
      stages: {
        translation: createTranslationStage("https://api.kluster.ai/v1", "deepseek-ai/DeepSeek-R1", [
          { id: "kluster-deepseek-r1", label: "deepseek-ai/DeepSeek-R1", apiModel: "deepseek-ai/DeepSeek-R1" },
        ]),
      },
    },
  {
      id: "siliconflow",
      name: "SiliconFlow",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://cloud.siliconflow.cn/",
      setupUrl: "https://cloud.siliconflow.cn/account/ak",
      limitsUrl: "https://cloud.siliconflow.cn/",
      rateLimitsUrl: "https://cloud.siliconflow.cn/",
      setupSummary: "Crie uma API key no console SiliconFlow e use o endpoint OpenAI-compatible oficial.",
      limitsSummary: "The referenced list reports 1,000 RPM and 50k TPM on the free tier for eligible models.",
      rateLimitSummary: "1,000 RPM and 50k TPM on the free tier, varying per model/region.",
      stages: {
        translation: createTranslationStage("https://api.siliconflow.cn/v1", "Qwen/Qwen3-8B", [
          { id: "siliconflow-qwen3-8b", label: "Qwen3-8B", apiModel: "Qwen/Qwen3-8B" },
          {
            id: "siliconflow-deepseek-r1-distill-qwen-7b",
            label: "DeepSeek-R1-Distill-Qwen-7B",
            apiModel: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
          },
        ]),
        ocr: createOcrStage("https://api.siliconflow.cn/v1", "THUDM/GLM-4.1V-9B-Thinking", [
          {
            id: "siliconflow-glm-4.1v-9b-thinking",
            label: "GLM-4.1V-9B-Thinking",
            apiModel: "THUDM/GLM-4.1V-9B-Thinking",
          },
        ]),
      },
    },
  {
      id: "ollama_cloud",
      name: "Ollama Cloud",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.ollama.com/cloud",
      setupUrl: "https://ollama.com/settings/keys",
      limitsUrl: "https://docs.ollama.com/cloud",
      rateLimitsUrl: "https://docs.ollama.com/cloud",
      setupSummary: "Ollama Cloud uses the native Ollama API at `https://ollama.com` with a Bearer token and is now supported in the app translation flow.",
      limitsSummary: "Light-use free tier with one concurrent model; usage is metered by GPU time and session/week windows.",
      rateLimitSummary: "Sem grade tradicional RPM/RPD; o consumo e controlado por GPU time e politicas de uso leve.",
      stages: {
        translation: createTranslationStage(
          "https://ollama.com",
          "gpt-oss:120b",
          [
            { id: "ollama-cloud-gpt-oss-120b", label: "gpt-oss:120b", apiModel: "gpt-oss:120b" },
            { id: "ollama-cloud-deepseek-v3.2", label: "deepseek-v3.2", apiModel: "deepseek-v3.2" },
            { id: "ollama-cloud-qwen3.5", label: "qwen3.5", apiModel: "qwen3.5" },
            { id: "ollama-cloud-kimi-k2.5", label: "kimi-k2.5", apiModel: "kimi-k2.5" },
          ],
          true,
          {
            transport: "ollama_native",
            allowCustomModelInput: true,
            modelInputPlaceholder: "gpt-oss:120b",
          },
        ),
      },
    },
  {
      id: "google_cloud_vertex_ai",
      name: "Google Cloud Vertex AI",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://console.cloud.google.com/vertex-ai/model-garden",
      setupUrl: "https://console.cloud.google.com/vertex-ai",
      limitsUrl: "https://cloud.google.com/vertex-ai/generative-ai/docs/quotas",
      rateLimitsUrl: "https://cloud.google.com/vertex-ai/generative-ai/docs/start/openai#current_limitations",
      setupSummary: "Use the Vertex AI OpenAI-compatible endpoint with project/location and an IAM access token in the API key field.",
      limitsSummary: "Llama models are free while in preview; per-model limits (30-60 rpm) and per-project/region quotas apply.",
      rateLimitSummary: "Rate limits seguem quotas do projeto e do endpoint OpenAI-compatible.",
      stages: {
        translation: createTranslationStage(
          "https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{location}/endpoints/openapi",
          "google/gemini-2.5-flash",
          [
            {
              id: "vertex-gemini-25-flash",
              label: "Gemini 2.5 Flash",
              apiModel: "google/gemini-2.5-flash",
            },
            {
              id: "vertex-gemini-25-flash-lite",
              label: "Gemini 2.5 Flash-Lite",
              apiModel: "google/gemini-2.5-flash-lite",
            },
            {
              id: "vertex-gemini-25-pro",
              label: "Gemini 2.5 Pro",
              apiModel: "google/gemini-2.5-pro",
            },
            {
              id: "vertex-openai-gpt-oss-20b-maas",
              label: "GPT-OSS 20B",
              apiModel: "openai/gpt-oss-20b-maas",
            },
            {
              id: "vertex-openai-gpt-oss-120b-maas",
              label: "GPT-OSS 120B",
              apiModel: "openai/gpt-oss-120b-maas",
            },
            {
              id: "vertex-deepseek-v3-2",
              label: "DeepSeek V3.2",
              apiModel: "deepseek-ai/DeepSeek-V3.2",
            },
            {
              id: "vertex-qwen3-next-80b",
              label: "Qwen3 Next 80B A3B Instruct",
              apiModel: "qwen/qwen3-next-80b-a3b-instruct-maas",
            },
            ],
          true,
          {
            transport: "openai_compatible",
            defaultParams: { location: "us-central1" },
            configFields: [
              {
                id: "project_id",
                label: "Google Cloud Project ID",
                placeholder: "my-gcp-project",
                required: true,
                description: "Projeto com Vertex AI habilitado.",
              },
              {
                id: "location",
                label: "Vertex Location",
                placeholder: "us-central1",
                required: true,
                description: "Region of the OpenAI-compatible endpoint.",
              },
            ],
          },
        ),
        ocr: createOcrStage(
          "https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{location}/endpoints/openapi",
          "google/gemini-2.5-flash",
          [
            {
              id: "vertex-gemini-25-flash-ocr",
              label: "Gemini 2.5 Flash",
              apiModel: "google/gemini-2.5-flash",
            },
            {
              id: "vertex-gemini-25-pro-ocr",
              label: "Gemini 2.5 Pro",
              apiModel: "google/gemini-2.5-pro",
            },
            ],
          true,
          {
            transport: "openai_compatible",
            defaultParams: { location: "us-central1" },
            configFields: [
              {
                id: "project_id",
                label: "Google Cloud Project ID",
                placeholder: "my-gcp-project",
                required: true,
                description: "Projeto com Vertex AI habilitado.",
              },
              {
                id: "location",
                label: "Vertex Location",
                placeholder: "us-central1",
                required: true,
                description: "Region of the OpenAI-compatible endpoint.",
              },
            ],
          },
        ),
      },
    },
  {
      id: "fireworks",
      name: "Fireworks",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.fireworks.ai/",
      setupUrl: "https://fireworks.ai/",
      limitsUrl: "https://fireworks.ai/pricing",
      rateLimitsUrl: "https://docs.fireworks.ai/",
      setupSummary: "Provider with an initial trial credit (~US$1) for LLM inference.",
      limitsSummary: "Credito inicial limitado (trial), consumo por token/modelo.",
      rateLimitSummary: "Rate limits and throughput depend on the plan and the account.",
      stages: {
        translation: createTranslationStage("https://api.fireworks.ai/inference/v1", "accounts/fireworks/models/llama-v3p1-70b-instruct", [
          {
            id: "fireworks-llama-70b",
            label: "Llama 3.1 70B Instruct",
            apiModel: "accounts/fireworks/models/llama-v3p1-70b-instruct",
          },
          ]),
      },
    },
  {
      id: "baseten",
      name: "Baseten",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.baseten.co/",
      setupUrl: "https://app.baseten.co/",
      limitsUrl: "https://www.baseten.co/pricing",
      rateLimitsUrl: "https://docs.baseten.co/",
      setupSummary: "Platform with a trial credit (~US$30) for model deployment/hosting.",
      limitsSummary: "Compute-based usage with initial evaluation credits.",
      rateLimitSummary: "Rate limits variam por endpoint e plano de conta.",
      stages: {
        translation: createTranslationStage("https://inference.baseten.co/v1", "meta-llama/Llama-3.1-8B-Instruct", [
          { id: "baseten-llama-31-8b", label: "Llama 3.1 8B Instruct", apiModel: "meta-llama/Llama-3.1-8B-Instruct" },
          ]),
      },
    },
  {
      id: "nebius",
      name: "Nebius",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://studio.nebius.com/",
      setupUrl: "https://studio.nebius.com/",
      limitsUrl: "https://studio.nebius.com/",
      rateLimitsUrl: "https://studio.nebius.com/",
      setupSummary: "Offers trial credit (around US$1) for use with supported models.",
      limitsSummary: "Trial credits with an expiry date and billing once consumed.",
      rateLimitSummary: "Rate limits por conta/projeto.",
      stages: {
        translation: createTranslationStage("https://api.studio.nebius.com/v1", "meta-llama/Llama-3.1-70B-Instruct", [
          { id: "nebius-llama-31-70b", label: "Llama 3.1 70B Instruct", apiModel: "meta-llama/Llama-3.1-70B-Instruct" },
          ]),
      },
    },
  {
      id: "novita",
      name: "Novita",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://novita.ai/",
      setupUrl: "https://novita.ai/",
      limitsUrl: "https://novita.ai/",
      rateLimitsUrl: "https://novita.ai/",
      setupSummary: "Provider with an initial trial credit (around US$0.5) and a catalog of open models.",
      limitsSummary: "Trial credits valid for one year under the provider's policy.",
      rateLimitSummary: "Limites por plano e endpoint.",
      stages: {
        translation: createTranslationStage("https://api.novita.ai/v3/openai", "meta-llama/llama-3.1-70b-instruct", [
          { id: "novita-llama-31-70b", label: "Llama 3.1 70B Instruct", apiModel: "meta-llama/llama-3.1-70b-instruct" },
          ]),
      },
    },
  {
      id: "ai21",
      name: "AI21",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.ai21.com/reference/chat-completions-ref",
      setupUrl: "https://studio.ai21.com/",
      limitsUrl: "https://www.ai21.com/pricing",
      rateLimitsUrl: "https://docs.ai21.com/docs/authentication",
      setupSummary: "Generate your API key in AI21 Studio and use the OpenAI-compatible endpoint at /studio/v1.",
      limitsSummary: "Credito trial de US$10 por 3 meses; limites variam por plano/modelo.",
      rateLimitSummary: "Rate limits per account/model; verify them in the AI21 Studio dashboard.",
      stages: {
        translation: createTranslationStage(
          "https://api.ai21.com/studio/v1",
          "jamba-large",
          [
            { id: "ai21-jamba-large", label: "Jamba Large", apiModel: "jamba-large" },
            { id: "ai21-jamba-mini", label: "Jamba Mini", apiModel: "jamba-mini" },
            ],
        ),
      },
    },
  {
      id: "upstage",
      name: "Upstage",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://console.upstage.ai/docs",
      setupUrl: "https://console.upstage.ai/",
      limitsUrl: "https://console.upstage.ai/",
      rateLimitsUrl: "https://console.upstage.ai/",
      setupSummary: "Use API key da Upstage e endpoint OpenAI-compatible em /v1.",
      limitsSummary: "Credito trial de US$10 por 3 meses; limites variam por plano/modelo.",
      rateLimitSummary: "Rate limits per account/model in the Upstage console.",
      stages: {
        translation: createTranslationStage(
          "https://api.upstage.ai/v1",
          "syn-pro",
          [
            { id: "upstage-solar-pro", label: "Solar Pro (legacy)", apiModel: "solar-pro" },
            { id: "upstage-syn-pro", label: "Syn Pro", apiModel: "syn-pro" },
            ],
        ),
      },
    },
  {
      id: "nlp_cloud",
      name: "NLP Cloud",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.nlpcloud.com/",
      setupUrl: "https://nlpcloud.com/home/playground",
      limitsUrl: "https://nlpcloud.com/pricing",
      rateLimitsUrl: "https://docs.nlpcloud.com/",
      setupSummary: "Use the NLP Cloud token in the Authorization header; the trial requires phone verification.",
      limitsSummary: "US$15 trial credit; limits depend on the plan/model.",
      rateLimitSummary: "Rate limits per account/model, as stated in the official documentation.",
      stages: {
        translation: createTranslationStage(
          "https://api.nlpcloud.io/v1",
          "finetuned-llama-3-70b",
          [
            { id: "nlpcloud-dolphin-mixtral", label: "Dolphin Mixtral", apiModel: "dolphin-mixtral-8x7b" },
            { id: "nlpcloud-llama-3-70b", label: "Llama 3 70B", apiModel: "finetuned-llama-3-70b" },
            ],
          true,
          { transport: "nlp_cloud_chatbot" },
        ),
      },
    },
  {
      id: "alibaba_model_studio",
      name: "Alibaba Cloud Model Studio",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://www.alibabacloud.com/help/en/model-studio/",
      setupUrl: "https://bailian.console.alibabacloud.com/",
      limitsUrl: "https://www.alibabacloud.com/help/en/model-studio/",
      rateLimitsUrl: "https://www.alibabacloud.com/help/en/model-studio/",
      setupSummary: "Model Studio with starting credits and Qwen/open-source models.",
      limitsSummary: "Free quota of 1,000,000 tokens per model (trial).",
      rateLimitSummary: "Rate limits are applied per region/project.",
      stages: {
        translation: createTranslationStage("https://dashscope-intl.aliyuncs.com/compatible-mode/v1", "qwen-plus", [
          { id: "alibaba-qwen-plus", label: "Qwen Plus", apiModel: "qwen-plus" },
          ]),
      },
    },
  {
      id: "modal",
      name: "Modal",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://modal.com/docs/examples/vllm_openai_compatible",
      setupUrl: "https://modal.com/",
      limitsUrl: "https://modal.com/pricing",
      rateLimitsUrl: "https://modal.com/docs",
      setupSummary: "Configure your Modal app with an OpenAI-compatible endpoint and provide the workspace/app slug.",
      limitsSummary: "Credito free de US$5/mes (US$30/mes com metodo de pagamento).",
      rateLimitSummary: "Rate limits depend on your endpoint deployment and the active plan.",
      stages: {
        translation: createTranslationStage(
          "https://{workspace}--{app_slug}.modal.run/v1",
          "meta-llama/Meta-Llama-3.1-8B-Instruct",
          [
            {
              id: "modal-meta-llama-31-8b",
              label: "Meta Llama 3.1 8B Instruct",
              apiModel: "meta-llama/Meta-Llama-3.1-8B-Instruct",
            },
            {
              id: "modal-qwen25-7b",
              label: "Qwen 2.5 7B Instruct",
              apiModel: "Qwen/Qwen2.5-7B-Instruct",
            },
            ],
          true,
          {
            transport: "openai_compatible",
            configFields: [
              {
                id: "workspace",
                label: "Modal workspace",
                placeholder: "your-workspace",
                required: true,
                description: "Workspace where the app was published.",
              },
              {
                id: "app_slug",
                label: "Modal app slug",
                placeholder: "your-openai-app",
                required: true,
                description: "Slug of the app exposing the OpenAI-compatible API.",
              },
            ],
            allowCustomModelInput: true,
            modelInputPlaceholder: "meta-llama/Meta-Llama-3.1-8B-Instruct",
          },
        ),
      },
    },
  {
      id: "inference_net",
      name: "Inference.net",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://inference.net/",
      setupUrl: "https://inference.net/",
      limitsUrl: "https://inference.net/",
      rateLimitsUrl: "https://inference.net/",
      setupSummary: "Provider with an initial trial credit for open-model inference.",
      limitsSummary: "Credito inicial de US$1 + US$25 apos survey/validacao.",
      rateLimitSummary: "Rate limits vary per model/account.",
      stages: {
        translation: createTranslationStage("https://api.inference.net/v1", "openai/gpt-oss-20b", [
          { id: "inference-net-gpt-oss-20b", label: "GPT OSS 20B", apiModel: "openai/gpt-oss-20b" },
          ]),
      },
    },
  {
      id: "hyperbolic",
      name: "Hyperbolic",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.hyperbolic.xyz/",
      setupUrl: "https://app.hyperbolic.xyz/",
      limitsUrl: "https://app.hyperbolic.xyz/",
      rateLimitsUrl: "https://docs.hyperbolic.xyz/",
      setupSummary: "Account with trial credits for open and multimodal models.",
      limitsSummary: "US$1 initial trial credit for the available models.",
      rateLimitSummary: "Rate limits per account and endpoint, as shown in the dashboard.",
      stages: {
        translation: createTranslationStage("https://api.hyperbolic.xyz/v1", "meta-llama/llama-3.1-70b-instruct", [
          { id: "hyperbolic-deepseek-v3", label: "DeepSeek V3", apiModel: "DeepSeek V3" },
          { id: "hyperbolic-deepseek-v3-0324", label: "DeepSeek V3 0324", apiModel: "DeepSeek V3 0324" },
          {
            id: "hyperbolic-deepseek-ai-deepseek-r1-0528",
            label: "deepseek-ai/deepseek-r1-0528",
            apiModel: "deepseek-ai/deepseek-r1-0528",
          },
          { id: "hyperbolic-llama-3-1-405b-base", label: "Llama 3.1 405B Base", apiModel: "Llama 3.1 405B Base" },
          {
            id: "hyperbolic-llama-3-1-405b-instruct",
            label: "Llama 3.1 405B Instruct",
            apiModel: "Llama 3.1 405B Instruct",
          },
          {
            id: "hyperbolic-llama-31-70b",
            label: "Llama 3.1 70B Instruct",
            apiModel: "meta-llama/llama-3.1-70b-instruct",
          },
          { id: "hyperbolic-llama-3-1-8b-instruct", label: "Llama 3.1 8B Instruct", apiModel: "Llama 3.1 8B Instruct" },
          { id: "hyperbolic-llama-3-2-3b-instruct", label: "Llama 3.2 3B Instruct", apiModel: "Llama 3.2 3B Instruct" },
          { id: "hyperbolic-llama-3-3-70b-instruct", label: "Llama 3.3 70B Instruct", apiModel: "Llama 3.3 70B Instruct" },
          { id: "hyperbolic-openai-gpt-oss-120b", label: "openai/gpt-oss-120b", apiModel: "openai/gpt-oss-120b" },
          {
            id: "hyperbolic-openai-gpt-oss-120b-turbo",
            label: "openai/gpt-oss-120b-turbo",
            apiModel: "openai/gpt-oss-120b-turbo",
          },
          { id: "hyperbolic-openai-gpt-oss-20b", label: "openai/gpt-oss-20b", apiModel: "openai/gpt-oss-20b" },
          { id: "hyperbolic-qwen-qwq-32b", label: "Qwen QwQ 32B", apiModel: "Qwen QwQ 32B" },
          { id: "hyperbolic-qwen-qwen3-235b-a22b", label: "qwen/qwen3-235b-a22b", apiModel: "qwen/qwen3-235b-a22b" },
          {
            id: "hyperbolic-qwen-qwen3-235b-a22b-instruct-2507",
            label: "qwen/qwen3-235b-a22b-instruct-2507",
            apiModel: "qwen/qwen3-235b-a22b-instruct-2507",
          },
          {
            id: "hyperbolic-qwen-qwen3-coder-480b-a35b-instruct",
            label: "qwen/qwen3-coder-480b-a35b-instruct",
            apiModel: "qwen/qwen3-coder-480b-a35b-instruct",
          },
          {
            id: "hyperbolic-qwen-qwen3-next-80b-a3b-instruct",
            label: "qwen/qwen3-next-80b-a3b-instruct",
            apiModel: "qwen/qwen3-next-80b-a3b-instruct",
          },
          {
            id: "hyperbolic-qwen-qwen3-next-80b-a3b-thinking",
            label: "qwen/qwen3-next-80b-a3b-thinking",
            apiModel: "qwen/qwen3-next-80b-a3b-thinking",
          },
          { id: "hyperbolic-qwen2-5-72b-instruct", label: "Qwen2.5 72B Instruct", apiModel: "Qwen2.5 72B Instruct" },
          {
            id: "hyperbolic-qwen2-5-coder-32b-instruct",
            label: "Qwen2.5 Coder 32B Instruct",
            apiModel: "Qwen2.5 Coder 32B Instruct",
          },
          ]),
        ocr: createOcrStage("https://api.hyperbolic.xyz/v1", "Qwen/Qwen2.5-VL-72B-Instruct", [
          { id: "hyperbolic-pixtral-12b-2409", label: "Pixtral 12B (2409)", apiModel: "Pixtral 12B (2409)" },
          {
            id: "hyperbolic-qwen2.5-vl-72b",
            label: "Qwen 2.5 VL 72B",
            apiModel: "Qwen/Qwen2.5-VL-72B-Instruct",
          },
          {
            id: "hyperbolic-qwen2.5-vl-7b-instruct",
            label: "Qwen2.5 VL 7B Instruct",
            apiModel: "Qwen2.5 VL 7B Instruct",
          },
          ]),
      },
    },
  {
      id: "sambanova_cloud",
      name: "SambaNova Cloud",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.sambanova.ai/",
      setupUrl: "https://cloud.sambanova.ai/",
      limitsUrl: "https://docs.sambanova.ai/",
      rateLimitsUrl: "https://docs.sambanova.ai/",
      setupSummary: "SambaNova account with trial credits and open/proprietary models.",
      limitsSummary: "Credito trial de US$5 valido por 3 meses.",
      rateLimitSummary: "Rate limits per endpoint/model on the active plan.",
      stages: {
        translation: createTranslationStage("https://api.sambanova.ai/v1", "Meta-Llama-3.1-70B-Instruct", [
          {
            id: "sambanova-deepseek-ai-deepseek-r1-0528",
            label: "deepseek-ai/DeepSeek-R1-0528",
            apiModel: "deepseek-ai/DeepSeek-R1-0528",
          },
          {
            id: "sambanova-deepseek-ai-deepseek-r1-distill-llama-70b",
            label: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
            apiModel: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
          },
          {
            id: "sambanova-deepseek-ai-deepseek-v3-0324",
            label: "deepseek-ai/DeepSeek-V3-0324",
            apiModel: "deepseek-ai/DeepSeek-V3-0324",
          },
          {
            id: "sambanova-deepseek-ai-deepseek-v3-1",
            label: "deepseek-ai/DeepSeek-V3.1",
            apiModel: "deepseek-ai/DeepSeek-V3.1",
          },
          {
            id: "sambanova-deepseek-ai-deepseek-v3-1-terminus",
            label: "deepseek-ai/DeepSeek-V3.1-Terminus",
            apiModel: "deepseek-ai/DeepSeek-V3.1-Terminus",
          },
          {
            id: "sambanova-deepseek-ai-deepseek-v3-2",
            label: "deepseek-ai/DeepSeek-V3.2",
            apiModel: "deepseek-ai/DeepSeek-V3.2",
          },
          { id: "samba-llama-31-70b", label: "Llama 3.1 70B Instruct", apiModel: "Meta-Llama-3.1-70B-Instruct" },
          { id: "sambanova-llama-3-1-8b", label: "Llama 3.1 8B", apiModel: "Llama 3.1 8B" },
          { id: "sambanova-llama-3-3-70b", label: "Llama 3.3 70B", apiModel: "Llama 3.3 70B" },
          {
            id: "sambanova-llama-4-maverick-17b-128e-instruct",
            label: "Llama-4-Maverick-17B-128E-Instruct",
            apiModel: "Llama-4-Maverick-17B-128E-Instruct",
          },
          { id: "sambanova-minimaxai-minimax-m2-5", label: "minimaxai/minimax-m2.5", apiModel: "minimaxai/minimax-m2.5" },
          { id: "sambanova-openai-gpt-oss-120b", label: "openai/gpt-oss-120b", apiModel: "openai/gpt-oss-120b" },
          { id: "sambanova-qwen-qwen3-235b", label: "Qwen/Qwen3-235B", apiModel: "Qwen/Qwen3-235B" },
          { id: "sambanova-qwen-qwen3-32b", label: "Qwen/Qwen3-32B", apiModel: "Qwen/Qwen3-32B" },
          ]),
      },
    },
  {
      id: "scaleway_generative_apis",
      name: "Scaleway Generative APIs",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://console.scaleway.com/generative-api/models",
      setupUrl: "https://console.scaleway.com/",
      limitsUrl: "https://www.scaleway.com/en/pricing/",
      rateLimitsUrl: "https://www.scaleway.com/en/docs/generative-apis/",
      setupSummary: "Scaleway with an initial free token quota for its generative API.",
      limitsSummary: "Credito inicial de 1.000.000 tokens gratuitos.",
      rateLimitSummary: "Rate limits por projeto e por endpoint.",
      stages: {
        translation: createTranslationStage("https://api.scaleway.ai/v1", "qwen3-235b-a22b-instruct-2507", [
          {
            id: "scaleway-deepseek-r1-distill-llama-70b",
            label: "DeepSeek R1 Distill Llama 70B",
            apiModel: "DeepSeek R1 Distill Llama 70B",
          },
          {
            id: "scaleway-devstral-2-123b-instruct-2512",
            label: "devstral-2-123b-instruct-2512",
            apiModel: "devstral-2-123b-instruct-2512",
          },
          { id: "scaleway-gemma-3-27b-instruct", label: "Gemma 3 27B Instruct", apiModel: "Gemma 3 27B Instruct" },
          { id: "scaleway-gpt-oss-120b", label: "gpt-oss-120b", apiModel: "gpt-oss-120b" },
          { id: "scaleway-holo2-30b-a3b", label: "holo2-30b-a3b", apiModel: "holo2-30b-a3b" },
          { id: "scaleway-llama-3-1-8b-instruct", label: "Llama 3.1 8B Instruct", apiModel: "Llama 3.1 8B Instruct" },
          { id: "scaleway-llama-3-3-70b-instruct", label: "Llama 3.3 70B Instruct", apiModel: "Llama 3.3 70B Instruct" },
          { id: "scaleway-mistral-nemo-2407", label: "Mistral Nemo 2407", apiModel: "Mistral Nemo 2407" },
          {
            id: "scaleway-mistral-small-3-2-24b-instruct-2506",
            label: "mistral-small-3.2-24b-instruct-2506",
            apiModel: "mistral-small-3.2-24b-instruct-2506",
          },
          {
            id: "scaleway-qwen3-235b-a22b-instruct-2507",
            label: "qwen3-235b-a22b-instruct-2507",
            apiModel: "qwen3-235b-a22b-instruct-2507",
          },
          {
            id: "scaleway-qwen3-coder-30b-a3b-instruct",
            label: "qwen3-coder-30b-a3b-instruct",
            apiModel: "qwen3-coder-30b-a3b-instruct",
          },
          { id: "scaleway-voxtral-small-24b-2507", label: "voxtral-small-24b-2507", apiModel: "voxtral-small-24b-2507" },
          ]),
        ocr: createOcrStage("https://api.scaleway.ai/v1", "Pixtral 12B (2409)", [
          { id: "scaleway-pixtral-12b-2409", label: "Pixtral 12B (2409)", apiModel: "Pixtral 12B (2409)" },
          ]),
      },
    }
];
