import type { FreeAiProviderCatalogEntry } from "./freeAiProviderCatalog";
import {
  createCleanStage,
  LAST_VERIFIED_AT,
  createOcrStage,
  createTranslationStage,
} from "./freeAiProviderCatalogBuilders";

export const FREE_AI_PROVIDER_CATALOG_CORE: FreeAiProviderCatalogEntry[] = [
  {
      id: "openrouter",
      name: "OpenRouter",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://openrouter.ai/docs",
      setupUrl: "https://openrouter.ai/docs/api-keys",
      limitsUrl: "https://openrouter.ai/docs/api-reference/limits",
      rateLimitsUrl: "https://openrouter.ai/docs/api-reference/limits",
      setupSummary: "Crie uma API key em OpenRouter > API Keys e use o endpoint OpenAI-compatible.",
      limitsSummary:
        "20 req/min, 50 req/day; up to 1000 req/day with a US$10 lifetime top-up. Models share the quota.",
      rateLimitSummary: "Rate limits are global per account; check the limits endpoint.",
      stages: {
        translation: createTranslationStage("https://openrouter.ai/api/v1", "openai/gpt-oss-20b:free", [
          {
            id: "openrouter-arcee-ai-trinity-large-preview-free",
            label: "arcee-ai/trinity-large-preview:free",
            apiModel: "arcee-ai/trinity-large-preview:free",
          },
          {
            id: "openrouter-arcee-ai-trinity-mini-free",
            label: "arcee-ai/trinity-mini:free",
            apiModel: "arcee-ai/trinity-mini:free",
          },
          {
            id: "openrouter-cognitivecomputations-dolphin-mistral-24b-venice-edition-free",
            label: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
            apiModel: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
          },
          {
            id: "openrouter-gemma-3-12b-instruct",
            label: "Gemma 3 12B Instruct",
            apiModel: "google/gemma-3-12b-it:free",
          },
          {
            id: "openrouter-gemma-3-27b-instruct",
            label: "Gemma 3 27B Instruct",
            apiModel: "google/gemma-3-27b-it:free",
          },
          {
            id: "openrouter-gemma-3-4b-instruct",
            label: "Gemma 3 4B Instruct",
            apiModel: "google/gemma-3-4b-it:free",
          },
          {
            id: "openrouter-google-gemma-3n-e2b-it-free",
            label: "google/gemma-3n-e2b-it:free",
            apiModel: "google/gemma-3n-e2b-it:free",
          },
          {
            id: "openrouter-google-gemma-3n-e4b-it-free",
            label: "google/gemma-3n-e4b-it:free",
            apiModel: "google/gemma-3n-e4b-it:free",
          },
          {
            id: "openrouter-hermes-3-llama-3-1-405b",
            label: "Hermes 3 Llama 3.1 405B",
            apiModel: "nousresearch/hermes-3-llama-3.1-405b:free",
          },
          {
            id: "openrouter-liquid-lfm-2-5-1-2b-instruct-free",
            label: "liquid/lfm-2.5-1.2b-instruct:free",
            apiModel: "liquid/lfm-2.5-1.2b-instruct:free",
          },
          {
            id: "openrouter-liquid-lfm-2-5-1-2b-thinking-free",
            label: "liquid/lfm-2.5-1.2b-thinking:free",
            apiModel: "liquid/lfm-2.5-1.2b-thinking:free",
          },
          {
            id: "openrouter-llama-3-2-3b-instruct",
            label: "Llama 3.2 3B Instruct",
            apiModel: "meta-llama/llama-3.2-3b-instruct:free",
          },
          {
            id: "llama-3.3-70b-free",
            label: "Llama 3.3 70B Instruct",
            apiModel: "meta-llama/llama-3.3-70b-instruct:free",
          },
          {
            id: "openrouter-mistral-small-3-1-24b-instruct",
            label: "Mistral Small 3.1 24B Instruct",
            apiModel: "mistralai/mistral-small-3.1-24b-instruct:free",
          },
          {
            id: "openrouter-nvidia-nemotron-3-nano-30b-a3b-free",
            label: "nvidia/nemotron-3-nano-30b-a3b:free",
            apiModel: "nvidia/nemotron-3-nano-30b-a3b:free",
          },
          {
            id: "openrouter-nvidia-nemotron-nano-9b-v2-free",
            label: "nvidia/nemotron-nano-9b-v2:free",
            apiModel: "nvidia/nemotron-nano-9b-v2:free",
          },
          {
            id: "gpt-oss-120b-free",
            label: "openai/gpt-oss-120b:free",
            apiModel: "openai/gpt-oss-120b:free",
          },
          { id: "gpt-oss-20b-free", label: "openai/gpt-oss-20b:free", apiModel: "openai/gpt-oss-20b:free" },
          { id: "openrouter-qwen-qwen3-4b-free", label: "qwen/qwen3-4b:free", apiModel: "qwen/qwen3-4b:free" },
          {
            id: "openrouter-qwen-qwen3-coder-free",
            label: "qwen/qwen3-coder:free",
            apiModel: "qwen/qwen3-coder:free",
          },
          {
            id: "openrouter-qwen-qwen3-next-80b-a3b-instruct-free",
            label: "qwen/qwen3-next-80b-a3b-instruct:free",
            apiModel: "qwen/qwen3-next-80b-a3b-instruct:free",
          },
          { id: "qwen3-235b-free", label: "Qwen3 235B (free)", apiModel: "qwen/qwen3-235b-a22b:free" },
          {
            id: "openrouter-stepfun-step-3-5-flash-free",
            label: "stepfun/step-3.5-flash:free",
            apiModel: "stepfun/step-3.5-flash:free",
          },
          {
            id: "openrouter-upstage-solar-pro-3-free",
            label: "upstage/solar-pro-3:free",
            apiModel: "upstage/solar-pro-3:free",
          },
          { id: "openrouter-z-ai-glm-4-5-air-free", label: "z-ai/glm-4.5-air:free", apiModel: "z-ai/glm-4.5-air:free" },
          ]),
        ocr: createOcrStage("https://openrouter.ai/api/v1", "qwen/qwen2.5-vl-72b-instruct:free", [
          {
            id: "nemotron-nano-12b-v2-vl-free",
            label: "nvidia/nemotron-nano-12b-v2-vl:free",
            apiModel: "nvidia/nemotron-nano-12b-v2-vl:free",
          },
          {
            id: "qwen2.5-vl-72b-free",
            label: "Qwen 2.5 VL 72B (free)",
            apiModel: "qwen/qwen2.5-vl-72b-instruct:free",
          },
          ]),
        clean: createCleanStage("https://openrouter.ai/api/v1", "google/gemini-2.5-flash", [
          {
            id: "openrouter-clean-gemini-2.5-flash",
            label: "google/gemini-2.5-flash",
            apiModel: "google/gemini-2.5-flash",
            notes: "Latest version of Gemini Flash",
          },
          {
            id: "openrouter-clean-gpt-4o-mini",
            label: "openai/gpt-4o-mini",
            apiModel: "openai/gpt-4o-mini",
            notes: "OpenAI model with image editing support",
          },
          {
            id: "openrouter-clean-gpt-4o",
            label: "openai/gpt-4o",
            apiModel: "openai/gpt-4o",
            notes: "Multimodal OpenAI model for inpainting",
          },
          ],
          true,
          {
            allowCustomModelInput: true,
            modelInputPlaceholder: "google/gemini-2.5-flash",
          },
        ),
      },
    },
  {
      id: "groq",
      name: "Groq",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://console.groq.com/docs/openai",
      setupUrl: "https://console.groq.com/keys",
      limitsUrl: "https://console.groq.com/docs/models",
      rateLimitsUrl: "https://console.groq.com/docs/rate-limits",
      setupSummary: "Generate your API key in the Groq console and use the platform's OpenAI-compatible endpoint.",
      limitsSummary: "Daily limits and TPM vary per model (large models around 1k req/day).",
      rateLimitSummary: "Rate limits are applied per account/model; check the official table.",
      stages: {
        translation: createTranslationStage("https://api.groq.com/openai/v1", "llama-3.3-70b-versatile", [
          { id: "groq-groq-compound", label: "groq/compound", apiModel: "groq/compound" },
          { id: "groq-groq-compound-mini", label: "groq/compound-mini", apiModel: "groq/compound-mini" },
          { id: "groq-llama-3-1-8b", label: "llama-3.1-8b-instant", apiModel: "llama-3.1-8b-instant" },
          { id: "llama-3.3-70b", label: "Llama 3.3 70B Versatile", apiModel: "llama-3.3-70b-versatile" },
          {
            id: "groq-llama-4-scout-instruct",
            label: "meta-llama/llama-4-scout-17b-16e-instruct",
            apiModel: "meta-llama/llama-4-scout-17b-16e-instruct",
          },
          { id: "groq-openai-gpt-oss-120b", label: "openai/gpt-oss-120b", apiModel: "openai/gpt-oss-120b" },
          { id: "groq-openai-gpt-oss-20b", label: "openai/gpt-oss-20b", apiModel: "openai/gpt-oss-20b" },
          { id: "groq-qwen-qwen3-32b", label: "qwen/qwen3-32b", apiModel: "qwen/qwen3-32b" },
          ]),
        ocr: createOcrStage("https://api.groq.com/openai/v1", "meta-llama/llama-4-scout-17b-16e-instruct", [
          {
            id: "groq-llama-4-scout-vision",
            label: "meta-llama/llama-4-scout-17b-16e-instruct",
            apiModel: "meta-llama/llama-4-scout-17b-16e-instruct",
          },
          ]),
      },
    },
  {
      id: "huggingface_router",
      name: "Hugging Face Router",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://huggingface.co/docs/inference-providers/tasks/chat-completion",
      setupUrl: "https://huggingface.co/settings/tokens",
      limitsUrl: "https://huggingface.co/docs/api-inference/pricing",
      rateLimitsUrl: "https://huggingface.co/docs/api-inference/pricing",
      setupSummary: "Crie um token em Hugging Face Settings > Access Tokens e use no router OpenAI-compatible.",
      limitsSummary: "Credito free mensal (~US$0,10) e cobranca apos consumo por provedor/modelo.",
      rateLimitSummary: "Limites dependem do plano, credito e backend do provider.",
      stages: {
        translation: createTranslationStage("https://router.huggingface.co/v1", "meta-llama/Llama-3.3-70B-Instruct", [
          {
            id: "hf-llama-3.3-70b",
            label: "Meta Llama 3.3 70B Instruct",
            apiModel: "meta-llama/Llama-3.3-70B-Instruct",
          },
          {
            id: "hf-mistral-7b",
            label: "Mistral 7B Instruct",
            apiModel: "mistralai/Mistral-7B-Instruct-v0.3",
          },
          {
            id: "hf-qwen2.5-72b",
            label: "Qwen 2.5 72B Instruct",
            apiModel: "Qwen/Qwen2.5-72B-Instruct",
          },
          ]),
        ocr: createOcrStage("https://router.huggingface.co/v1", "Qwen/Qwen2.5-VL-72B-Instruct", [
          {
            id: "hf-qwen2.5-vl-72b",
            label: "Qwen 2.5 VL 72B",
            apiModel: "Qwen/Qwen2.5-VL-72B-Instruct",
          },
          ]),
        clean: createCleanStage("https://api-inference.huggingface.co/models", "stabilityai/stable-diffusion-2-inpainting", [
          {
            id: "hf-clean-sd2-inpainting",
            label: "Stable Diffusion 2 Inpainting",
            apiModel: "stabilityai/stable-diffusion-2-inpainting",
            notes: "Modelo classico de inpainting via Inference API",
          },
          {
            id: "hf-clean-sd15-inpainting",
            label: "Stable Diffusion 1.5 Inpainting",
            apiModel: "runwayml/stable-diffusion-inpainting",
            notes: "Inpainting leve e rapido via Inference API",
          },
          {
            id: "hf-clean-flux-fill-dev",
            label: "FLUX.1 Fill (dev)",
            apiModel: "black-forest-labs/FLUX.1-Fill-dev",
            notes: "Inpainting de alta qualidade via Inference API",
          },
          ],
          true,
          {
            transport: "openai_compatible",
            allowCustomModelInput: true,
            modelInputPlaceholder: "stabilityai/stable-diffusion-2-inpainting",
          },
        ),
      },
    },
  {
      id: "cerebras",
      name: "Cerebras",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://inference-docs.cerebras.ai/resources/openai",
      setupUrl: "https://inference-docs.cerebras.ai/api-reference/authentication",
      limitsUrl: "https://inference-docs.cerebras.ai/support/rate-limits",
      rateLimitsUrl: "https://inference-docs.cerebras.ai/support/rate-limits",
      setupSummary: "Generate your API key in the Cerebras dashboard and use the OpenAI-compatible endpoint.",
      limitsSummary: "Per-model limits (generally 30 rpm/60k TPM; GLM-4.6 at 10 rpm).",
      rateLimitSummary: "Rate limits per model/account, as published in the official Cerebras table.",
      stages: {
        translation: createTranslationStage("https://api.cerebras.ai/v1", "llama-3.3-70b", [
          { id: "cerebras-gpt-oss-120b", label: "gpt-oss-120b", apiModel: "gpt-oss-120b" },
          { id: "cerebras-llama-3.1-8b", label: "llama3.1-8b", apiModel: "llama3.1-8b" },
          { id: "cerebras-llama-3.3-70b", label: "Llama 3.3 70B", apiModel: "llama-3.3-70b" },
          {
            id: "cerebras-qwen-3-235b-a22b-instruct",
            label: "qwen-3-235b-a22b-instruct-2507",
            apiModel: "qwen-3-235b-a22b-instruct-2507",
          },
          { id: "cerebras-qwen-3-32b", label: "Qwen 3 32B", apiModel: "qwen-3-32b" },
          { id: "cerebras-z-ai-glm-4-6", label: "z-ai/glm-4.5-air", apiModel: "z-ai/glm-4.5-air" },
          ]),
      },
    },
  {
      id: "openai",
      name: "OpenAI",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://platform.openai.com/docs/api-reference",
      setupUrl: "https://platform.openai.com/api-keys",
      limitsUrl: "https://platform.openai.com/docs/guides/rate-limits",
      rateLimitsUrl: "https://platform.openai.com/docs/guides/rate-limits",
      setupSummary: "Create an API key on the OpenAI platform to use GPT directly in the BYOK flow.",
      limitsSummary: "Limits vary by account, organization and model; check the official OpenAI dashboard.",
      rateLimitSummary: "Rate limits are applied per account/model and may vary with usage and verification.",
      stages: {
        translation: createTranslationStage("https://api.openai.com/v1", "gpt-4.1-mini", [
          { id: "openai-gpt-4.1-mini", label: "GPT-4.1 mini", apiModel: "gpt-4.1-mini" },
          { id: "openai-gpt-4.1", label: "GPT-4.1", apiModel: "gpt-4.1" },
          { id: "openai-gpt-4o-mini", label: "GPT-4o mini", apiModel: "gpt-4o-mini" },
        ]),
        ocr: createOcrStage("https://api.openai.com/v1", "gpt-4.1-mini", [
          { id: "openai-gpt-4.1-mini-ocr", label: "GPT-4.1 mini", apiModel: "gpt-4.1-mini" },
          { id: "openai-gpt-4o-ocr", label: "GPT-4o", apiModel: "gpt-4o" },
        ]),
        clean: createCleanStage("https://api.openai.com/v1", "gpt-4o", [
          { id: "openai-gpt-4o-clean", label: "GPT-4o", apiModel: "gpt-4o", notes: "Multimodal OpenAI model for cleaning/inpainting workflows." },
          { id: "openai-gpt-4o-mini-clean", label: "GPT-4o mini", apiModel: "gpt-4o-mini" },
        ]),
      },
    },
  {
      id: "deepseek",
      name: "DeepSeek",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://api-docs.deepseek.com/",
      setupUrl: "https://platform.deepseek.com/api_keys",
      limitsUrl: "https://api-docs.deepseek.com/quick_start/rate_limit",
      rateLimitsUrl: "https://api-docs.deepseek.com/quick_start/rate_limit",
      setupSummary: "Create an API key on the DeepSeek platform to use the chat/reasoner models in the BYOK flow.",
      limitsSummary: "Limits and pricing vary by model; check the official DeepSeek table.",
      rateLimitSummary: "Rate limits are applied per account and model as described in the official documentation.",
      stages: {
        translation: createTranslationStage("https://api.deepseek.com/v1", "deepseek-chat", [
          { id: "deepseek-chat", label: "DeepSeek Chat", apiModel: "deepseek-chat" },
          { id: "deepseek-reasoner", label: "DeepSeek Reasoner", apiModel: "deepseek-reasoner" },
        ]),
      },
    },
  {
      id: "xai",
      name: "xAI",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.x.ai/developers/models",
      setupUrl: "https://console.x.ai/",
      limitsUrl: "https://docs.x.ai/developers/models",
      rateLimitsUrl: "https://docs.x.ai/developers/models",
      setupSummary: "Generate your API key in the xAI console to use Grok through an OpenAI-compatible endpoint.",
      limitsSummary: "Per-model/per-account limits vary; check the official xAI documentation.",
      rateLimitSummary: "Quotas are applied per account and per selected Grok model.",
      stages: {
        translation: createTranslationStage("https://api.x.ai/v1", "grok-4", [
          { id: "xai-grok-4", label: "Grok 4", apiModel: "grok-4" },
          { id: "xai-grok-4-latest", label: "Grok 4 Latest", apiModel: "grok-4-latest" },
        ]),
        ocr: createOcrStage("https://api.x.ai/v1", "grok-4", [
          { id: "xai-grok-4-vision", label: "Grok 4", apiModel: "grok-4" },
          { id: "xai-grok-4-latest-vision", label: "Grok 4 Latest", apiModel: "grok-4-latest" },
        ]),
      },
    },
  {
      id: "z_ai",
      name: "Z.AI",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.z.ai/",
      setupUrl: "https://platform.z.ai/",
      limitsUrl: "https://docs.z.ai/",
      rateLimitsUrl: "https://docs.z.ai/",
      setupSummary: "Use your Z.AI API key to call GLM models in the BYOK flow through a compatible endpoint.",
      limitsSummary: "Limits and quotas depend on the Z.AI plan/model you subscribe to.",
      rateLimitSummary: "Rate limits and throughput vary per GLM model and account.",
      stages: {
        translation: createTranslationStage("https://api.z.ai/api/paas/v4", "glm-4.5", [
          { id: "zai-glm-4.5", label: "GLM-4.5", apiModel: "glm-4.5" },
        ]),
        ocr: createOcrStage("https://api.z.ai/api/paas/v4", "glm-4.5v", [
          { id: "zai-glm-4.5v", label: "GLM-4.5V", apiModel: "glm-4.5v" },
        ]),
      },
    },
  {
      id: "google_ai_studio",
      name: "Google AI Studio",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://ai.google.dev/gemini-api/docs",
      setupUrl: "https://aistudio.google.com/app/apikey",
      limitsUrl: "https://ai.google.dev/gemini-api/docs/rate-limits",
      rateLimitsUrl: "https://ai.google.dev/gemini-api/docs/rate-limits",
      setupSummary: "Create your API key in Google AI Studio to call Gemini/Gemma models through the API.",
      limitsSummary:
        "Data may be used for training outside the UK/CH/EEA/EU. Per-model limits: Gemini around 250k TPM/20 req-day/5-10 rpm; Gemma around 15k TPM/14.4k req-day/30 rpm.",
      rateLimitSummary: "Rate limits vary per model/region; check the AI Studio table.",
      stages: {
        translation: createTranslationStage(
          "https://generativelanguage.googleapis.com/v1beta/models",
          "gemini-2.5-flash",
          [
            { id: "google-gemini-2.5-flash", label: "Gemini 2.5 Flash", apiModel: "gemini-2.5-flash" },
            {
              id: "google-gemini-2.5-flash-lite",
              label: "Gemini 2.5 Flash-Lite",
              apiModel: "gemini-2.5-flash-lite",
            },
            { id: "google-gemini-2.5-pro", label: "Gemini 2.5 Pro", apiModel: "gemini-2.5-pro" },
            { id: "google-gemma-3-12b", label: "Gemma 3 12B Instruct", apiModel: "gemma-3-12b-it" },
            { id: "google-gemma-3-1b", label: "Gemma 3 1B Instruct", apiModel: "gemma-3-1b-it" },
            { id: "google-gemma-3-27b", label: "Gemma 3 27B Instruct", apiModel: "gemma-3-27b-it" },
            { id: "google-gemma-3-4b", label: "Gemma 3 4B Instruct", apiModel: "gemma-3-4b-it" },
            ],
          true,
          { transport: "gemini_native" },
        ),
        ocr: createOcrStage(
          "https://generativelanguage.googleapis.com/v1beta/models",
          "gemini-2.5-flash",
          [
            { id: "google-gemini-2.5-flash-ocr", label: "Gemini 2.5 Flash", apiModel: "gemini-2.5-flash" },
            {
              id: "google-gemini-2.5-flash-lite-ocr",
              label: "Gemini 2.5 Flash-Lite",
              apiModel: "gemini-2.5-flash-lite",
            },
            { id: "google-gemini-2.5-pro-ocr", label: "Gemini 2.5 Pro", apiModel: "gemini-2.5-pro" },
            ],
          true,
          { transport: "gemini_native" },
        ),
        clean: createCleanStage(
          "https://generativelanguage.googleapis.com/v1beta/models",
          "gemini-2.5-flash-image",
          [
            { id: "google-gemini-2.5-flash-image-clean", label: "Gemini 2.5 Flash Image", apiModel: "gemini-2.5-flash-image", notes: "Model with image editing/generation support" },
            { id: "google-gemini-2.5-flash-clean", label: "Gemini 2.5 Flash", apiModel: "gemini-2.5-flash", notes: "Versao mais recente, free tier generoso" },
            ],
          true,
          { transport: "gemini_native" },
        ),
      },
    },
  {
      id: "replicate",
      name: "Replicate",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://replicate.com/docs",
      setupUrl: "https://replicate.com/account/api-tokens",
      limitsUrl: "https://replicate.com/docs/dedicated-ips#rate-limits",
      rateLimitsUrl: "https://replicate.com/docs/dedicated-ips#rate-limits",
      setupSummary: "Generate your API key in Replicate > Account > API Tokens. Use inpainting/text-removal models through the OpenAI-compatible API or call the model directly.",
      limitsSummary: "Credito trial inicial (~US$1). Modelos de inpainting custam ~$0.0004-$0.01/run.",
      rateLimitSummary: "Rate limits are per account; shared models have concurrency limits.",
      stages: {
        clean: createCleanStage("https://api.replicate.com/v1", "dpakkk/image-object-removal", [
          {
            id: "replicate-dpakkk-image-object-removal",
            label: "Image Object Removal",
            apiModel: "dpakkk/image-object-removal:6f2e72772f0da8f37c10d2eb0e4e8c8e8b4e8e8e8e8e8e8e8e8e8e8e8e8e8e8e",
            notes: "~$0.00044/run, ideal for removing text from images",
          },
          {
            id: "replicate-flux-kontext-text-removal",
            label: "FLUX.1 Kontext Text Removal",
            apiModel: "black-forest-labs/flux-kontext-pro",
            notes: "Model specialized in text removal via FLUX",
          },
          {
            id: "replicate-adirik-inst-inpaint",
            label: "Inst-Inpaint (Text-Guided Object Removal)",
            apiModel: "adirik/inst-inpaint:3d07e5d1e1c7e4e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8",
            notes: "Remocao de objetos guiada por texto via difus\u00e3o",
          },
          ],
          true,
          {
            allowCustomModelInput: true,
            modelInputPlaceholder: "dpakkk/image-object-removal:version",
          },
        ),
      },
    },
  {
      id: "nvidia_nim",
      name: "NVIDIA NIM",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://build.nvidia.com/",
      setupUrl: "https://build.nvidia.com/",
      limitsUrl: "https://build.nvidia.com/",
      rateLimitsUrl: "https://build.nvidia.com/",
      setupSummary: "Access through an NVIDIA account with phone verification and an API key from Build.",
      limitsSummary: "Free limit is around 40 req/min, with limited context/models.",
      rateLimitSummary: "Rate limits vary per model; check the NVIDIA Build dashboard.",
      stages: {
        translation: createTranslationStage("https://integrate.api.nvidia.com/v1", "meta/llama-3.1-8b-instruct", [
          { id: "nvidia-llama-31-8b", label: "Llama 3.1 8B Instruct", apiModel: "meta/llama-3.1-8b-instruct" },
          ]),
      },
    },
  {
      id: "mistral_plateforme",
      name: "Mistral (La Plateforme)",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.mistral.ai/",
      setupUrl: "https://console.mistral.ai/",
      limitsUrl: "https://docs.mistral.ai/getting-started/rate-limits/",
      rateLimitsUrl: "https://docs.mistral.ai/getting-started/rate-limits/",
      setupSummary: "Create an API key on the Mistral platform; the free tier requires data-usage opt-in and phone verification.",
      limitsSummary: "Free tier: 1 rps, 500k TPM and 1B tokens/month (may vary per account/model).",
      rateLimitSummary: "Rate limits per model and plan; check the official Mistral table.",
      stages: {
        translation: createTranslationStage("https://api.mistral.ai/v1", "mistral-small-latest", [
          { id: "mistral-small-latest", label: "Mistral Small", apiModel: "mistral-small-latest" },
          ]),
      },
    },
  {
      id: "mistral_codestral",
      name: "Mistral (Codestral)",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://codestral.mistral.ai/",
      setupUrl: "https://codestral.mistral.ai/",
      limitsUrl: "https://codestral.mistral.ai/",
      rateLimitsUrl: "https://codestral.mistral.ai/",
      setupSummary: "Access focused on code models; requires phone verification.",
      limitsSummary: "Free: ~30 rpm e ~2.000 requests/dia (pode variar).",
      rateLimitSummary: "Official rate limits per model/account; check the Codestral dashboard.",
      stages: {
        translation: createTranslationStage("https://codestral.mistral.ai/v1", "codestral-latest", [
          { id: "codestral-latest", label: "Codestral Latest", apiModel: "codestral-latest" },
          ]),
      },
    },
  {
      id: "vercel_ai_gateway",
      name: "Vercel AI Gateway",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://vercel.com/docs/ai-gateway",
      setupUrl: "https://vercel.com/docs/ai-gateway",
      limitsUrl: "https://vercel.com/pricing",
      rateLimitsUrl: "https://vercel.com/docs/ai-gateway",
      setupSummary: "Configure the Vercel project and provider routing in the AI Gateway.",
      limitsSummary: "Credito mensal (cerca de US$5) dependendo do plano Vercel.",
      rateLimitSummary: "Rate limits and throughput depend on the plan and the routed providers.",
      stages: {
        translation: createTranslationStage("https://ai-gateway.vercel.sh/v1", "openai/gpt-oss-20b", [
          { id: "vercel-gateway-openai-gpt-oss-20b", label: "Gateway -> GPT OSS 20B", apiModel: "openai/gpt-oss-20b" },
          ]),
      },
    },
  {
      id: "cohere",
      name: "Cohere",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://docs.cohere.com/",
      setupUrl: "https://dashboard.cohere.com/api-keys",
      limitsUrl: "https://docs.cohere.com/docs/rate-limits",
      rateLimitsUrl: "https://docs.cohere.com/docs/rate-limits",
      setupSummary: "Create a key in the Cohere dashboard and use the Command/Aya models on the official endpoint.",
      limitsSummary: "Plano free: cerca de 20 rpm e 1.000 requests/mensais.",
      rateLimitSummary: "Rate limits and monthly quotas are applied per account.",
      stages: {
        translation: createTranslationStage("https://api.cohere.ai/compatibility/v1", "command-a-03-2025", [
          { id: "cohere-c4ai-aya-expanse-32b", label: "c4ai-aya-expanse-32b", apiModel: "c4ai-aya-expanse-32b" },
          { id: "cohere-command-a-03-2025", label: "command-a-03-2025", apiModel: "command-a-03-2025" },
          {
            id: "cohere-command-a-reasoning-08-2025",
            label: "command-a-reasoning-08-2025",
            apiModel: "command-a-reasoning-08-2025",
          },
          {
            id: "cohere-command-a-translate-08-2025",
            label: "command-a-translate-08-2025",
            apiModel: "command-a-translate-08-2025",
          },
          { id: "cohere-command-r-08-2024", label: "command-r-08-2024", apiModel: "command-r-08-2024" },
          { id: "cohere-command-r-plus-08-2024", label: "command-r-plus-08-2024", apiModel: "command-r-plus-08-2024" },
          { id: "cohere-command-r7b-12-2024", label: "command-r7b-12-2024", apiModel: "command-r7b-12-2024" },
          ]),
        ocr: createOcrStage("https://api.cohere.ai/compatibility/v1", "command-a-vision-07-2025", [
          { id: "cohere-c4ai-aya-vision-32b", label: "c4ai-aya-vision-32b", apiModel: "c4ai-aya-vision-32b" },
          {
            id: "cohere-command-a-vision-07-2025",
            label: "command-a-vision-07-2025",
            apiModel: "command-a-vision-07-2025",
          },
          ]),
      },
    },
  {
      id: "github_models",
      name: "GitHub Models",
      status: "integrated",
      lastVerifiedAt: LAST_VERIFIED_AT,
      docsUrl: "https://github.com/marketplace/models",
      setupUrl: "https://github.com/settings/tokens",
      limitsUrl: "https://docs.github.com/en/github-models/prototyping-with-ai-models#rate-limits",
      rateLimitsUrl: "https://docs.github.com/en/github-models/prototyping-with-ai-models#rate-limits",
      setupSummary: "Create a GitHub token with permission for GitHub Models.",
      limitsSummary: "Limites dependem do tier do Copilot (Free/Pro/Business/Enterprise); free e bem restrito.",
      rateLimitSummary: "Rate limits de tokens/requests variam por tier e modelo.",
      stages: {
        translation: createTranslationStage("https://models.inference.ai.azure.com", "gpt-4o-mini", [
          { id: "github-ai21-jamba-1-5-large", label: "AI21 Jamba 1.5 Large", apiModel: "AI21 Jamba 1.5 Large" },
          { id: "github-codestral-25-01", label: "Codestral 25.01", apiModel: "Codestral 25.01" },
          { id: "github-cohere-command-a", label: "Cohere Command A", apiModel: "Cohere Command A" },
          {
            id: "github-cohere-command-r-08-2024",
            label: "Cohere Command R 08-2024",
            apiModel: "Cohere Command R 08-2024",
          },
          {
            id: "github-cohere-command-r-plus-08-2024",
            label: "Cohere Command R+ 08-2024",
            apiModel: "Cohere Command R+ 08-2024",
          },
          { id: "github-deepseek-r1", label: "DeepSeek-R1", apiModel: "DeepSeek-R1" },
          { id: "github-deepseek-r1-0528", label: "DeepSeek-R1-0528", apiModel: "DeepSeek-R1-0528" },
          { id: "github-deepseek-v3-0324", label: "DeepSeek-V3-0324", apiModel: "DeepSeek-V3-0324" },
          { id: "github-gpt-4o-mini", label: "GPT-4o mini", apiModel: "gpt-4o-mini" },
          { id: "github-grok-3", label: "Grok 3", apiModel: "grok-3" },
          { id: "github-grok-3-mini", label: "Grok 3 Mini", apiModel: "grok-3-mini" },
          {
            id: "github-llama-4-maverick-17b-128e-instruct-fp8",
            label: "Llama 4 Maverick 17B 128E Instruct FP8",
            apiModel: "Llama 4 Maverick 17B 128E Instruct FP8",
          },
          {
            id: "github-llama-4-scout-17b-16e-instruct",
            label: "Llama 4 Scout 17B 16E Instruct",
            apiModel: "Llama 4 Scout 17B 16E Instruct",
          },
          {
            id: "github-llama-3-3-70b-instruct",
            label: "Llama-3.3-70B-Instruct",
            apiModel: "Llama-3.3-70B-Instruct",
          },
          { id: "github-mai-ds-r1", label: "MAI-DS-R1", apiModel: "MAI-DS-R1" },
          {
            id: "github-meta-llama-3-1-405b-instruct",
            label: "Meta-Llama-3.1-405B-Instruct",
            apiModel: "Meta-Llama-3.1-405B-Instruct",
          },
          {
            id: "github-meta-llama-3-1-8b-instruct",
            label: "Meta-Llama-3.1-8B-Instruct",
            apiModel: "Meta-Llama-3.1-8B-Instruct",
          },
          { id: "github-ministral-3b", label: "Ministral 3B", apiModel: "Ministral 3B" },
          { id: "github-mistral-medium-3-25-05", label: "Mistral Medium 3 (25.05)", apiModel: "Mistral Medium 3 (25.05)" },
          { id: "github-mistral-small-3-1", label: "Mistral Small 3.1", apiModel: "Mistral Small 3.1" },
          { id: "github-openai-gpt-4-1", label: "OpenAI GPT-4.1", apiModel: "gpt-4.1" },
          { id: "github-openai-gpt-4-1-mini", label: "OpenAI GPT-4.1-mini", apiModel: "gpt-4.1-mini" },
          { id: "github-openai-gpt-4-1-nano", label: "OpenAI GPT-4.1-nano", apiModel: "gpt-4.1-nano" },
          { id: "github-openai-gpt-4o", label: "OpenAI GPT-4o", apiModel: "gpt-4o" },
          { id: "github-openai-gpt-4o-mini", label: "OpenAI GPT-4o mini", apiModel: "gpt-4o-mini" },
          { id: "github-openai-gpt-5", label: "OpenAI gpt-5", apiModel: "gpt-5" },
          { id: "github-openai-gpt-5-mini", label: "OpenAI gpt-5-mini", apiModel: "gpt-5-mini" },
          { id: "github-openai-gpt-5-nano", label: "OpenAI gpt-5-nano", apiModel: "gpt-5-nano" },
          { id: "github-openai-o1", label: "OpenAI o1", apiModel: "o1" },
          { id: "github-openai-o1-mini", label: "OpenAI o1-mini", apiModel: "o1-mini" },
          { id: "github-openai-o3", label: "OpenAI o3", apiModel: "o3" },
          { id: "github-openai-o3-mini", label: "OpenAI o3-mini", apiModel: "o3-mini" },
          { id: "github-openai-o4-mini", label: "OpenAI o4-mini", apiModel: "o4-mini" },
          { id: "github-phi-4", label: "Phi-4", apiModel: "Phi-4" },
          { id: "github-phi-4-mini-instruct", label: "Phi-4-mini-instruct", apiModel: "Phi-4-mini-instruct" },
          { id: "github-phi-4-mini-reasoning", label: "Phi-4-mini-reasoning", apiModel: "Phi-4-mini-reasoning" },
          { id: "github-phi-4-reasoning", label: "Phi-4-reasoning", apiModel: "Phi-4-reasoning" },
          ]),
        ocr: createOcrStage("https://models.inference.ai.azure.com", "gpt-4o", [
          { id: "github-openai-gpt-4o-ocr", label: "OpenAI GPT-4o", apiModel: "gpt-4o" },
          {
            id: "github-phi-4-multimodal-instruct",
            label: "Phi-4-multimodal-instruct",
            apiModel: "Phi-4-multimodal-instruct",
          },
          ]),
      },
    }
];
