import type { NativeTextEffectPreset } from "./textEffects";

export const NATIVE_TEXT_EFFECT_PRESETS: NativeTextEffectPreset[] = [
  {
    id: "none",
    label: "typography.effect.none.label",
    description: "typography.effect.none.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
  },
  {
    id: "balloon_smear",
    label: "typography.effect.balloon_smear.label",
    description: "typography.effect.balloon_smear.description",
    supportsIntensity: true,
    ghostLayers: 7,
    offsetYStep: 6,
    offsetXAmplitude: 1.8,
    blurStart: 0.8,
    blurStep: 0.7,
    opacityStart: 0.18,
    opacityFalloff: 0.82,
    fill: "rgba(110, 110, 110, 0.92)",
    recommendedPatch: {
      bold: true,
      italic: true,
      uppercase: true,
      alignment: "center",
      lineSpacing: 0.92,
      outlineWidth: 0,
      outlineOpacity: 0,
      shadowEnabled: false,
      shadowOpacity: 0,
      shadowBlur: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      gradientEnabled: false,
      detectGradient: false,
      color: "#111111",
      fillCssValue: "#111111",
    },
  },
  {
    id: "smiles_outline",
    label: "typography.effect.smiles_outline.label",
    description: "typography.effect.smiles_outline.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#fff7f5",
      fillCssValue: "#fff7f5",
      outlineColor: "#f2a59d",
      outlineOpacity: 1,
      outlineWidth: 2.6,
      shadowEnabled: true,
      shadowColor: "#ffd7d2",
      shadowOpacity: 0.42,
      shadowBlur: 7,
      shadowOffsetX: 0,
      shadowOffsetY: 1,
      italic: false,
      bold: false,
      uppercase: false,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "ahnnn_peach",
    label: "typography.effect.ahnnn_peach.label",
    description: "typography.effect.ahnnn_peach.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(255,196,176,0.9)",
    recommendedPatch: {
      color: "#f4b39e",
      fillCssValue: "#f4b39e",
      outlineWidth: 0,
      shadowEnabled: true,
      italic: false,
      bold: false,
      uppercase: false,
      gradientEnabled: false,
      detectGradient: false,
      shadowFillCssValue: "#ffd1be",
      shadowGradientEnabled: false,
      shadowGradientStartColor: "#ffd1be",
      shadowGradientEndColor: "#ffd1be",
      shadowGradientAngle: 90,
      shadowOpacity: 0.42,
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
    },
  },
  {
    id: "silence_ink",
    label: "typography.effect.silence_ink.label",
    description: "typography.effect.silence_ink.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#8d90d9",
      fillCssValue: "#8d90d9",
      outlineColor: "#27234f",
      outlineOpacity: 1,
      outlineWidth: 1.8,
      shadowEnabled: true,
      shadowColor: "#d7d9ff",
      shadowOpacity: 0.18,
      shadowBlur: 2.4,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      italic: true,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "hwa_pastel",
    label: "typography.effect.hwa_pastel.label",
    description: "typography.effect.hwa_pastel.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#eef09a",
      fillCssValue: "#eef09a",
      outlineColor: "#e9a6db",
      outlineOpacity: 1,
      outlineWidth: 2.4,
      shadowEnabled: true,
      shadowColor: "#fff6c8",
      shadowOpacity: 0.28,
      shadowBlur: 4.5,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      italic: false,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "hah_pop",
    label: "typography.effect.hah_pop.label",
    description: "typography.effect.hah_pop.description",
    shadowLayers: [
      { fillCssValue: "#f4b8dd", opacity: 0.72, blur: 0, offsetX: -5, offsetY: 4 },
    ],
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#eee6ff",
      fillCssValue: "#eee6ff",
      outlineColor: "#9b8cff",
      outlineOpacity: 1,
      outlineWidth: 2.8,
      shadowEnabled: true,
      shadowColor: "#f4b8dd",
      shadowFillCssValue: "#f4b8dd",
      shadowGradientEnabled: false,
      shadowGradientStartColor: "#f4b8dd",
      shadowGradientEndColor: "#f4b8dd",
      shadowGradientAngle: 90,
      shadowOpacity: 0.55,
      shadowBlur: 0,
      shadowOffsetX: -4,
      shadowOffsetY: 4,
      italic: false,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "smooch_jelly",
    label: "typography.effect.smooch_jelly.label",
    description: "typography.effect.smooch_jelly.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#ffb4ab",
      fillCssValue: "linear-gradient(180deg, #ffd7cf 0%, #ff8e86 100%)",
      gradientEnabled: true,
      gradientStartColor: "#ffd7cf",
      gradientEndColor: "#ff8e86",
      gradientAngle: 180,
      detectGradient: false,
      outlineColor: "#fff8f7",
      outlineOpacity: 1,
      outlineWidth: 1.6,
      shadowEnabled: true,
      shadowColor: "#f36c6c",
      shadowOpacity: 0.42,
      shadowBlur: 3,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      italic: false,
      bold: true,
      uppercase: false,
    },
  },
  {
    id: "tremble_brush",
    label: "typography.effect.tremble_brush.label",
    description: "typography.effect.tremble_brush.description",
    supportsIntensity: true,
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(55, 99, 233, 0.92)",
    recommendedPatch: {
      color: "#2d5fe0",
      fillCssValue: "linear-gradient(180deg, #2d5fe0 0%, #6a2fd8 100%)",
      gradientEnabled: true,
      gradientStartColor: "#2d5fe0",
      gradientEndColor: "#6a2fd8",
      gradientAngle: 180,
      detectGradient: false,
      outlineWidth: 0,
      shadowEnabled: false,
      italic: false,
      bold: true,
      uppercase: true,
    },
  },
  {
    id: "eheheh_whisper",
    label: "typography.effect.eheheh_whisper.label",
    description: "typography.effect.eheheh_whisper.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#fff6f8",
      fillCssValue: "#fff6f8",
      outlineColor: "#f09fb3",
      outlineOpacity: 1,
      outlineWidth: 2.3,
      shadowEnabled: true,
      shadowColor: "#ffc7d4",
      shadowOpacity: 0.38,
      shadowBlur: 6.5,
      shadowOffsetX: 0,
      shadowOffsetY: 1,
      italic: false,
      bold: false,
      uppercase: false,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "hoho_ink",
    label: "typography.effect.hoho_ink.label",
    description: "typography.effect.hoho_ink.description",
    supportsIntensity: true,
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(50, 79, 112, 0.88)",
    recommendedPatch: {
      color: "#314f70",
      fillCssValue: "#314f70",
      outlineWidth: 0,
      shadowEnabled: false,
      italic: false,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "blam_impact",
    label: "typography.effect.blam_impact.label",
    description: "typography.effect.blam_impact.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#ffcc00",
      fillCssValue: "linear-gradient(180deg, #ffd941 0%, #ff9f00 100%)",
      gradientEnabled: true,
      gradientStartColor: "#ffd941",
      gradientEndColor: "#ff9f00",
      gradientAngle: 180,
      detectGradient: false,
      outlineColor: "#fff1a8",
      outlineOpacity: 1,
      outlineWidth: 1.4,
      shadowEnabled: true,
      shadowColor: "#d92d2d",
      shadowOpacity: 0.92,
      shadowBlur: 0,
      shadowOffsetX: -3,
      shadowOffsetY: 4,
      italic: true,
      bold: true,
      uppercase: true,
    },
  },
  {
    id: "badump_soft",
    label: "typography.effect.badump_soft.label",
    description: "typography.effect.badump_soft.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#e4a7e9",
      fillCssValue: "linear-gradient(180deg, #d793e6 0%, #f5c7a0 100%)",
      gradientEnabled: true,
      gradientStartColor: "#d793e6",
      gradientEndColor: "#f5c7a0",
      gradientAngle: 180,
      detectGradient: false,
      outlineWidth: 0,
      shadowEnabled: true,
      shadowColor: "#ffe1cd",
      shadowOpacity: 0.28,
      shadowBlur: 5,
      shadowOffsetX: 0,
      shadowOffsetY: 1,
      italic: false,
      bold: true,
      uppercase: true,
    },
  },
  {
    id: "thump_heavy",
    label: "typography.effect.thump_heavy.label",
    description: "typography.effect.thump_heavy.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#111111",
      fillCssValue: "#111111",
      outlineWidth: 0,
      shadowEnabled: true,
      shadowColor: "#7a1018",
      shadowOpacity: 0.95,
      shadowBlur: 0,
      shadowOffsetX: -3,
      shadowOffsetY: 2,
      italic: true,
      bold: true,
      uppercase: true,
    },
  },
  {
    id: "neon_woah",
    label: "typography.effect.neon_woah.label",
    description: "typography.effect.neon_woah.description",
    shadowLayers: [
      { fillCssValue: "#ffffff", opacity: 0.9, blur: 6, offsetX: 0, offsetY: 0 },
      { fillCssValue: "#ff47c9", opacity: 0.8, blur: 12, offsetX: 0, offsetY: 0 },
      { fillCssValue: "#ff47c9", opacity: 0.58, blur: 24, offsetX: 0, offsetY: 0 },
    ],
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(255, 71, 201, 0.9)",
    recommendedPatch: {
      color: "#fff8fd",
      fillCssValue: "#fff8fd",
      outlineWidth: 0,
      shadowEnabled: true,
      shadowColor: "#ff47c9",
      shadowFillCssValue: "#ff47c9",
      shadowGradientEnabled: false,
      shadowGradientStartColor: "#ff47c9",
      shadowGradientEndColor: "#ff47c9",
      shadowGradientAngle: 90,
      shadowOpacity: 0.78,
      shadowBlur: 12,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      italic: false,
      bold: false,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "slash_speed",
    label: "typography.effect.slash_speed.label",
    description: "typography.effect.slash_speed.description",
    supportsIntensity: true,
    ghostLayers: 6,
    offsetYStep: 3,
    offsetXAmplitude: 6.5,
    blurStart: 1.5,
    blurStep: 1,
    opacityStart: 0.12,
    opacityFalloff: 0.8,
    fill: "rgba(80, 0, 110, 0.82)",
    recommendedPatch: {
      color: "#170b22",
      fillCssValue: "#170b22",
      outlineWidth: 0,
      shadowEnabled: false,
      italic: true,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "ah_teal",
    label: "typography.effect.ah_teal.label",
    description: "typography.effect.ah_teal.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#29e2c9",
      fillCssValue: "#29e2c9",
      outlineColor: "#16616a",
      outlineOpacity: 1,
      outlineWidth: 2.2,
      shadowEnabled: false,
      italic: false,
      bold: true,
      uppercase: false,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "drip_blue",
    label: "typography.effect.drip_blue.label",
    description: "typography.effect.drip_blue.description",
    supportsIntensity: true,
    ghostLayers: 4,
    offsetYStep: 4.5,
    offsetXAmplitude: 0.6,
    blurStart: 0.8,
    blurStep: 0.6,
    opacityStart: 0.08,
    opacityFalloff: 0.86,
    fill: "rgba(135, 208, 255, 0.52)",
    recommendedPatch: {
      color: "#e6fbff",
      fillCssValue: "#e6fbff",
      outlineColor: "#5ca4ff",
      outlineOpacity: 1,
      outlineWidth: 2.1,
      shadowEnabled: false,
      italic: false,
      bold: false,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "question_pop",
    label: "typography.effect.question_pop.label",
    description: "typography.effect.question_pop.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#ffca62",
      fillCssValue: "linear-gradient(180deg, #ffd88a 0%, #ffae5a 100%)",
      gradientEnabled: true,
      gradientStartColor: "#ffd88a",
      gradientEndColor: "#ffae5a",
      gradientAngle: 180,
      detectGradient: false,
      outlineColor: "#fff8df",
      outlineOpacity: 0.9,
      outlineWidth: 1.2,
      shadowEnabled: true,
      shadowColor: "#ff8c60",
      shadowOpacity: 0.74,
      shadowBlur: 0,
      shadowOffsetX: -2,
      shadowOffsetY: 3,
      italic: false,
      bold: true,
      uppercase: true,
    },
  },
  {
    id: "laugh_curve",
    label: "typography.effect.laugh_curve.label",
    description: "typography.effect.laugh_curve.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#92ffff",
      fillCssValue: "#92ffff",
      outlineWidth: 0,
      shadowEnabled: true,
      shadowColor: "#44cde0",
      shadowOpacity: 0.42,
      shadowBlur: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      italic: false,
      bold: false,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "shake_blur",
    label: "typography.effect.shake_blur.label",
    description: "typography.effect.shake_blur.description",
    supportsIntensity: true,
    ghostLayers: 5,
    offsetYStep: 2.5,
    offsetXAmplitude: 3.4,
    blurStart: 1.2,
    blurStep: 0.7,
    opacityStart: 0.1,
    opacityFalloff: 0.82,
    fill: "rgba(88, 58, 214, 0.72)",
    recommendedPatch: {
      color: "#3d1fd1",
      fillCssValue: "#3d1fd1",
      outlineWidth: 0,
      shadowEnabled: false,
      italic: true,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "beep_outline",
    label: "typography.effect.beep_outline.label",
    description: "typography.effect.beep_outline.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#ffffff",
      fillCssValue: "#ffffff",
      outlineColor: "#111111",
      outlineOpacity: 1,
      outlineWidth: 3.2,
      shadowEnabled: false,
      italic: false,
      bold: true,
      uppercase: false,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "boom_comic",
    label: "typography.effect.boom_comic.label",
    description: "typography.effect.boom_comic.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#ffd327",
      fillCssValue: "linear-gradient(180deg, #ffe152 0%, #ff9d22 100%)",
      gradientEnabled: true,
      gradientStartColor: "#ffe152",
      gradientEndColor: "#ff9d22",
      gradientAngle: 180,
      detectGradient: false,
      outlineColor: "#9c1b19",
      outlineOpacity: 1,
      outlineWidth: 2.8,
      shadowEnabled: false,
      italic: true,
      bold: true,
      uppercase: true,
    },
  },
  {
    id: "bang_chunk",
    label: "typography.effect.bang_chunk.label",
    description: "typography.effect.bang_chunk.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#2a22c5",
      fillCssValue: "linear-gradient(180deg, #2d2bdc 0%, #3019aa 100%)",
      gradientEnabled: true,
      gradientStartColor: "#2d2bdc",
      gradientEndColor: "#3019aa",
      gradientAngle: 180,
      detectGradient: false,
      outlineColor: "#c8962d",
      outlineOpacity: 1,
      outlineWidth: 3.4,
      shadowEnabled: true,
      shadowColor: "#c8962d",
      shadowOpacity: 0.9,
      shadowBlur: 0,
      shadowOffsetX: -3,
      shadowOffsetY: 4,
      italic: true,
      bold: true,
      uppercase: true,
    },
  },
  {
    id: "break_glitch",
    label: "typography.effect.break_glitch.label",
    description: "typography.effect.break_glitch.description",
    ghostLayers: 4,
    offsetYStep: 1.5,
    offsetXAmplitude: 2.4,
    blurStart: 0.4,
    blurStep: 0.4,
    opacityStart: 0.08,
    opacityFalloff: 0.84,
    fill: "rgba(118, 15, 88, 0.58)",
    recommendedPatch: {
      color: "#7a115f",
      fillCssValue: "#7a115f",
      outlineWidth: 0,
      shadowEnabled: false,
      italic: false,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "flinch_outline",
    label: "typography.effect.flinch_outline.label",
    description: "typography.effect.flinch_outline.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#d71919",
      fillCssValue: "#d71919",
      outlineColor: "#ffffff",
      outlineOpacity: 1,
      outlineWidth: 3,
      shadowEnabled: true,
      shadowColor: "#111111",
      shadowOpacity: 1,
      shadowBlur: 0,
      shadowOffsetX: -2,
      shadowOffsetY: 2,
      italic: true,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "growl_moss",
    label: "typography.effect.growl_moss.label",
    description: "typography.effect.growl_moss.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#a7a64a",
      fillCssValue: "#a7a64a",
      outlineWidth: 0,
      shadowEnabled: false,
      italic: false,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "yawn_soft",
    label: "typography.effect.yawn_soft.label",
    description: "typography.effect.yawn_soft.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#a8dd2e",
      fillCssValue: "#a8dd2e",
      outlineColor: "#5a1f78",
      outlineOpacity: 1,
      outlineWidth: 2.2,
      shadowEnabled: false,
      italic: false,
      bold: true,
      uppercase: false,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "scratch_noise",
    label: "typography.effect.scratch_noise.label",
    description: "typography.effect.scratch_noise.description",
    supportsIntensity: true,
    ghostLayers: 5,
    offsetYStep: 0.8,
    offsetXAmplitude: 1.8,
    blurStart: 0.2,
    blurStep: 0.2,
    opacityStart: 0.08,
    opacityFalloff: 0.88,
    fill: "rgba(0,0,0,0.45)",
    recommendedPatch: {
      color: "#111111",
      fillCssValue: "#111111",
      outlineWidth: 0,
      shadowEnabled: false,
      italic: false,
      bold: false,
      uppercase: false,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "crack_ink",
    label: "typography.effect.crack_ink.label",
    description: "typography.effect.crack_ink.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#111111",
      fillCssValue: "#111111",
      outlineWidth: 0,
      shadowEnabled: false,
      italic: true,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "slap_scratch",
    label: "typography.effect.slap_scratch.label",
    description: "typography.effect.slap_scratch.description",
    supportsIntensity: true,
    ghostLayers: 5,
    offsetYStep: 1.2,
    offsetXAmplitude: 5.8,
    blurStart: 0.6,
    blurStep: 0.5,
    opacityStart: 0.08,
    opacityFalloff: 0.82,
    fill: "rgba(32, 0, 40, 0.5)",
    recommendedPatch: {
      color: "#18051d",
      fillCssValue: "#18051d",
      outlineWidth: 0,
      shadowEnabled: false,
      italic: true,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "dash_edge",
    label: "typography.effect.dash_edge.label",
    description: "typography.effect.dash_edge.description",
    ghostLayers: 0,
    offsetYStep: 0,
    offsetXAmplitude: 0,
    blurStart: 0,
    blurStep: 0,
    opacityStart: 0,
    opacityFalloff: 1,
    fill: "rgba(0,0,0,0)",
    recommendedPatch: {
      color: "#e9f1f0",
      fillCssValue: "#e9f1f0",
      outlineColor: "#496f46",
      outlineOpacity: 1,
      outlineWidth: 2.2,
      shadowEnabled: true,
      shadowColor: "#496f46",
      shadowOpacity: 0.7,
      shadowBlur: 0,
      shadowOffsetX: -1,
      shadowOffsetY: 2,
      italic: true,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
  {
    id: "scream_scratch",
    label: "typography.effect.scream_scratch.label",
    description: "typography.effect.scream_scratch.description",
    supportsIntensity: true,
    ghostLayers: 3,
    offsetYStep: 0.8,
    offsetXAmplitude: 1.6,
    blurStart: 0.2,
    blurStep: 0.2,
    opacityStart: 0.08,
    opacityFalloff: 0.9,
    fill: "rgba(180, 0, 0, 0.38)",
    recommendedPatch: {
      color: "#111111",
      fillCssValue: "#111111",
      outlineWidth: 0,
      shadowEnabled: true,
      shadowColor: "#cc0000",
      shadowOpacity: 0.8,
      shadowBlur: 0,
      shadowOffsetX: -1,
      shadowOffsetY: 1,
      italic: true,
      bold: true,
      uppercase: true,
      gradientEnabled: false,
      detectGradient: false,
    },
  },
];
